/*
 * Created on 10 五月 2015 ( Time 21:36:20 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.datajpa.business.service;

import java.util.List;

import com.dt.hippo.datajpa.model.jpa.Account;

/**
 * Business Service Interface for entity Account.
 */
public interface AccountService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param id
	 * @return entity
	 */
	Account findById( Long id  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Account> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Account save(Account entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Account update(Account entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Account create(Account entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param id
	 */
	void delete( Long id );


}
