/*
 * Created on 21 ���� 2014 ( Time 16:43:28 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.datajpa.business.service;

import java.util.List;

import com.dt.hippo.datajpa.model.jpa.Hobby;

/**
 * Business Service Interface for entity Hobby.
 */
public interface HobbyService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param hobbyId
	 * @return entity
	 */
	Hobby findById( String hobbyId  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Hobby> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Hobby save(Hobby entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Hobby update(Hobby entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Hobby create(Hobby entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param hobbyId
	 */
	void delete( String hobbyId );


}
