/*
 * Created on 30 五月 2015 ( Time 18:22:33 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service;

import java.util.List;

import com.dt.hippo.auto.model.Adlist;

/**
 * Business Service Interface for entity Adlist.
 */
public interface AdlistService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param uid
	 * @return entity
	 */
	Adlist findById( Long uid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Adlist> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Adlist save(Adlist entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Adlist update(Adlist entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Adlist create(Adlist entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param uid
	 */
	void delete( Long uid );


}
