/*
 * Created on 12 五月 2015 ( Time 20:53:00 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service;

import java.util.List;

import com.dt.hippo.auto.model.Administrator;

/**
 * Business Service Interface for entity Administrator.
 */
public interface AdministratorService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param uid
	 * @return entity
	 */
	Administrator findById( Long uid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Administrator> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Administrator save(Administrator entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Administrator update(Administrator entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Administrator create(Administrator entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param uid
	 */
	void delete( Long uid );


}
