/*
 * Created on 12 五月 2015 ( Time 20:53:03 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service;

import java.util.List;

import com.dt.hippo.auto.model.Mediaresource;

/**
 * Business Service Interface for entity Mediaresource.
 */
public interface MediaresourceService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param uid
	 * @return entity
	 */
	Mediaresource findById( Long uid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Mediaresource> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Mediaresource save(Mediaresource entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Mediaresource update(Mediaresource entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Mediaresource create(Mediaresource entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param uid
	 */
	void delete( Long uid );


}
