/*
 * Created on 13 五月 2015 ( Time 21:15:29 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service;

import java.util.List;

import com.dt.hippo.auto.model.Promotiondetailinfo;

/**
 * Business Service Interface for entity Promotiondetailinfo.
 */
public interface PromotiondetailinfoService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param uid
	 * @param dishid
	 * @param specificationid
	 * @return entity
	 */
	Promotiondetailinfo findById( Long uid, Long dishid, Long specificationid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Promotiondetailinfo> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Promotiondetailinfo save(Promotiondetailinfo entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Promotiondetailinfo update(Promotiondetailinfo entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Promotiondetailinfo create(Promotiondetailinfo entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param uid
	 * @param dishid
	 * @param specificationid
	 */
	void delete( Long uid, Long dishid, Long specificationid );


}
