/*
 * Created on 13 五月 2015 ( Time 21:15:32 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service;

import java.util.List;

import com.dt.hippo.auto.model.Systemparameter;

/**
 * Business Service Interface for entity Systemparameter.
 */
public interface SystemparameterService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param uid
	 * @return entity
	 */
	Systemparameter findById( Integer uid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Systemparameter> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Systemparameter save(Systemparameter entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Systemparameter update(Systemparameter entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Systemparameter create(Systemparameter entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param uid
	 */
	void delete( Integer uid );


}
