/*
 * Created on 18 五月 2015 ( Time 11:07:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service;

import java.util.List;

import com.dt.hippo.auto.model.Verifyrecord;

/**
 * Business Service Interface for entity Verifyrecord.
 */
public interface VerifyrecordService { 

	/**
	 * Loads an entity from the database using its Primary Key
	 * @param uid
	 * @return entity
	 */
	Verifyrecord findById( Long uid  ) ;

	/**
	 * Loads all entities.
	 * @return all entities
	 */
	List<Verifyrecord> findAll();

	/**
	 * Saves the given entity in the database (create or update)
	 * @param entity
	 * @return entity
	 */
	Verifyrecord save(Verifyrecord entity);

	/**
	 * Updates the given entity in the database
	 * @param entity
	 * @return
	 */
	Verifyrecord update(Verifyrecord entity);

	/**
	 * Creates the given entity in the database
	 * @param entity
	 * @return
	 */
	Verifyrecord create(Verifyrecord entity);

	/**
	 * Deletes an entity using its Primary Key
	 * @param uid
	 */
	void delete( Long uid );


}
