/*
 * Created on 13 五月 2015 ( Time 21:15:29 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.web.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;
import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

//--- Common classes
import com.dt.hippo.auto.web.common.AbstractController;
import com.dt.hippo.auto.web.common.FormMode;
import com.dt.hippo.auto.web.common.Message;
import com.dt.hippo.auto.web.common.MessageType;

//--- Entities
import com.dt.hippo.auto.model.Promotiondetailinfo;
import com.dt.hippo.auto.model.Dishinfo;
import com.dt.hippo.auto.model.Dishspecificationinfo;

//--- Services 
import com.dt.hippo.auto.business.service.PromotiondetailinfoService;
import com.dt.hippo.auto.business.service.DishinfoService;
import com.dt.hippo.auto.business.service.DishspecificationinfoService;

//--- List Items 
import com.dt.hippo.auto.web.listitem.DishinfoListItem;
import com.dt.hippo.auto.web.listitem.DishspecificationinfoListItem;

/**
 * Spring MVC controller for 'Promotiondetailinfo' management.
 */
@Controller
@RequestMapping("/promotiondetailinfo")
public class PromotiondetailinfoController extends AbstractController {

	//--- Variables names ( to be used in JSP with Expression Language )
	private static final String MAIN_ENTITY_NAME = "promotiondetailinfo";
	private static final String MAIN_LIST_NAME   = "list";

	//--- JSP pages names ( View name in the MVC model )
	private static final String JSP_FORM   = "promotiondetailinfo/form";
	private static final String JSP_LIST   = "promotiondetailinfo/list";

	//--- SAVE ACTION ( in the HTML form )
	private static final String SAVE_ACTION_CREATE   = "/promotiondetailinfo/create";
	private static final String SAVE_ACTION_UPDATE   = "/promotiondetailinfo/update";

	//--- Main entity service
	@Resource
    protected PromotiondetailinfoService promotiondetailinfoService; // Injected by Spring
	//--- Other service(s)
	@Resource
    protected DishinfoService dishinfoService; // Injected by Spring
	@Resource
    protected DishspecificationinfoService dishspecificationinfoService; // Injected by Spring

	//--------------------------------------------------------------------------------------
	/**
	 * Default constructor
	 */
	public PromotiondetailinfoController() {
		super(PromotiondetailinfoController.class, MAIN_ENTITY_NAME );
		log("PromotiondetailinfoController created.");
	}

	//--------------------------------------------------------------------------------------
	// Spring MVC model management
	//--------------------------------------------------------------------------------------
	/**
	 * Populates the combo-box "items" for the referenced entity "Dishinfo"
	 * @param model
	 */
	private void populateListOfDishinfoItems(Model model) {
		List<Dishinfo> list = dishinfoService.findAll();
		List<DishinfoListItem> items = new LinkedList<DishinfoListItem>();
		for ( Dishinfo dishinfo : list ) {
			items.add(new DishinfoListItem( dishinfo ) );
		}
		model.addAttribute("listOfDishinfoItems", items ) ;
	}

	/**
	 * Populates the combo-box "items" for the referenced entity "Dishspecificationinfo"
	 * @param model
	 */
	private void populateListOfDishspecificationinfoItems(Model model) {
		List<Dishspecificationinfo> list = dishspecificationinfoService.findAll();
		List<DishspecificationinfoListItem> items = new LinkedList<DishspecificationinfoListItem>();
		for ( Dishspecificationinfo dishspecificationinfo : list ) {
			items.add(new DishspecificationinfoListItem( dishspecificationinfo ) );
		}
		model.addAttribute("listOfDishspecificationinfoItems", items ) ;
	}


	/**
	 * Populates the Spring MVC model with the given entity and eventually other useful data
	 * @param model
	 * @param promotiondetailinfo
	 */
	private void populateModel(Model model, Promotiondetailinfo promotiondetailinfo, FormMode formMode) {
		//--- Main entity
		model.addAttribute(MAIN_ENTITY_NAME, promotiondetailinfo);
		if ( formMode == FormMode.CREATE ) {
			model.addAttribute(MODE, MODE_CREATE); // The form is in "create" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_CREATE); 			
			//--- Other data useful in this screen in "create" mode (all fields)
			populateListOfDishinfoItems(model);
			populateListOfDishspecificationinfoItems(model);
		}
		else if ( formMode == FormMode.UPDATE ) {
			model.addAttribute(MODE, MODE_UPDATE); // The form is in "update" mode
			model.addAttribute(SAVE_ACTION, SAVE_ACTION_UPDATE); 			
			//--- Other data useful in this screen in "update" mode (only non-pk fields)
		}
	}

	//--------------------------------------------------------------------------------------
	// Request mapping
	//--------------------------------------------------------------------------------------
	/**
	 * Shows a list with all the occurrences of Promotiondetailinfo found in the database
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping()
	public String list(Model model) {
		log("Action 'list'");
		List<Promotiondetailinfo> list = promotiondetailinfoService.findAll();
		model.addAttribute(MAIN_LIST_NAME, list);		
		return JSP_LIST;
	}

	/**
	 * Shows a form page in order to create a new Promotiondetailinfo
	 * @param model Spring MVC model
	 * @return
	 */
	@RequestMapping("/form")
	public String formForCreate(Model model) {
		log("Action 'formForCreate'");
		//--- Populates the model with a new instance
		Promotiondetailinfo promotiondetailinfo = new Promotiondetailinfo();	
		populateModel( model, promotiondetailinfo, FormMode.CREATE);
		return JSP_FORM;
	}

	/**
	 * Shows a form page in order to update an existing Promotiondetailinfo
	 * @param model Spring MVC model
	 * @param uid  primary key element
	 * @param dishid  primary key element
	 * @param specificationid  primary key element
	 * @return
	 */
	@RequestMapping(value = "/form/{uid}/{dishid}/{specificationid}")
	public String formForUpdate(Model model, @PathVariable("uid") Long uid, @PathVariable("dishid") Long dishid, @PathVariable("specificationid") Long specificationid ) {
		log("Action 'formForUpdate'");
		//--- Search the entity by its primary key and stores it in the model 
		Promotiondetailinfo promotiondetailinfo = promotiondetailinfoService.findById(uid, dishid, specificationid);
		populateModel( model, promotiondetailinfo, FormMode.UPDATE);		
		return JSP_FORM;
	}

	/**
	 * 'CREATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param promotiondetailinfo  entity to be created
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/create" ) // GET or POST
	public String create(@Valid Promotiondetailinfo promotiondetailinfo, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'create'");
		try {
			if (!bindingResult.hasErrors()) {
				Promotiondetailinfo promotiondetailinfoCreated = promotiondetailinfoService.create(promotiondetailinfo); 
				model.addAttribute(MAIN_ENTITY_NAME, promotiondetailinfoCreated);

				//---
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				return redirectToForm(httpServletRequest, promotiondetailinfo.getUid(), promotiondetailinfo.getDishid(), promotiondetailinfo.getSpecificationid() );
			} else {
				populateModel( model, promotiondetailinfo, FormMode.CREATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			log("Action 'create' : Exception - " + e.getMessage() );
			messageHelper.addException(model, "promotiondetailinfo.error.create", e);
			populateModel( model, promotiondetailinfo, FormMode.CREATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'UPDATE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param promotiondetailinfo  entity to be updated
	 * @param bindingResult Spring MVC binding result
	 * @param model Spring MVC model
	 * @param redirectAttributes Spring MVC redirect attributes
	 * @param httpServletRequest
	 * @return
	 */
	@RequestMapping(value = "/update" ) // GET or POST
	public String update(@Valid Promotiondetailinfo promotiondetailinfo, BindingResult bindingResult, Model model, RedirectAttributes redirectAttributes, HttpServletRequest httpServletRequest) {
		log("Action 'update'");
		try {
			if (!bindingResult.hasErrors()) {
				//--- Perform database operations
				Promotiondetailinfo promotiondetailinfoSaved = promotiondetailinfoService.update(promotiondetailinfo);
				model.addAttribute(MAIN_ENTITY_NAME, promotiondetailinfoSaved);
				//--- Set the result message
				messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"save.ok"));
				log("Action 'update' : update done - redirect");
				return redirectToForm(httpServletRequest, promotiondetailinfo.getUid(), promotiondetailinfo.getDishid(), promotiondetailinfo.getSpecificationid());
			} else {
				log("Action 'update' : binding errors");
				populateModel( model, promotiondetailinfo, FormMode.UPDATE);
				return JSP_FORM;
			}
		} catch(Exception e) {
			messageHelper.addException(model, "promotiondetailinfo.error.update", e);
			log("Action 'update' : Exception - " + e.getMessage() );
			populateModel( model, promotiondetailinfo, FormMode.UPDATE);
			return JSP_FORM;
		}
	}

	/**
	 * 'DELETE' action processing. <br>
	 * This action is based on the 'Post/Redirect/Get (PRG)' pattern, so it ends by 'http redirect'<br>
	 * @param redirectAttributes
	 * @param uid  primary key element
	 * @param dishid  primary key element
	 * @param specificationid  primary key element
	 * @return
	 */
	@RequestMapping(value = "/delete/{uid}/{dishid}/{specificationid}") // GET or POST
	public String delete(RedirectAttributes redirectAttributes, @PathVariable("uid") Long uid, @PathVariable("dishid") Long dishid, @PathVariable("specificationid") Long specificationid) {
		log("Action 'delete'" );
		try {
			promotiondetailinfoService.delete( uid, dishid, specificationid );
			//--- Set the result message
			messageHelper.addMessage(redirectAttributes, new Message(MessageType.SUCCESS,"delete.ok"));	
		} catch(Exception e) {
			messageHelper.addException(redirectAttributes, "promotiondetailinfo.error.delete", e);
		}
		return redirectToList();
	}

}
