/*
 * Created on 18 五月 2015 ( Time 17:57:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model.base;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Comboinfo extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    protected Long uid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    protected Long dishid;


    protected Long specificationid;


    protected Long corpid;


    protected Integer placeholder;


    protected Integer orderinplaceholder;


    protected Integer amount;


    protected Long pricedifference;


    protected Date createdate;


    protected Date modifydate;

    @Size( max = 50 )
    protected String createuser;

    @Size( max = 50 )
    protected String modifyuser;


    protected Integer status;

    @Size( max = 50 )
    protected String platform;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }

    public Long getUid() {
        return this.uid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setDishid( Long dishid ) {
        this.dishid = dishid;
    }
    public Long getDishid() {
        return this.dishid;
    }

    public void setSpecificationid( Long specificationid ) {
        this.specificationid = specificationid;
    }
    public Long getSpecificationid() {
        return this.specificationid;
    }

    public void setCorpid( Long corpid ) {
        this.corpid = corpid;
    }
    public Long getCorpid() {
        return this.corpid;
    }

    public void setPlaceholder( Integer placeholder ) {
        this.placeholder = placeholder;
    }
    public Integer getPlaceholder() {
        return this.placeholder;
    }

    public void setOrderinplaceholder( Integer orderinplaceholder ) {
        this.orderinplaceholder = orderinplaceholder;
    }
    public Integer getOrderinplaceholder() {
        return this.orderinplaceholder;
    }

    public void setAmount( Integer amount ) {
        this.amount = amount;
    }
    public Integer getAmount() {
        return this.amount;
    }

    public void setPricedifference( Long pricedifference ) {
        this.pricedifference = pricedifference;
    }
    public Long getPricedifference() {
        return this.pricedifference;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(uid);
        sb.append("|");
        sb.append(dishid);
        sb.append("|");
        sb.append(specificationid);
        sb.append("|");
        sb.append(corpid);
        sb.append("|");
        sb.append(placeholder);
        sb.append("|");
        sb.append(orderinplaceholder);
        sb.append("|");
        sb.append(amount);
        sb.append("|");
        sb.append(pricedifference);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 


}
