/*
 * Created on 25 五月 2015 ( Time 11:17:28 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model.base;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Dishinfo extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    protected Long uid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    protected Long corpid;

    @Size( max = 10 )
    protected String no;

    @NotNull
    @Size( min = 1, max = 5 )
    protected String categoryid;

    @NotNull
    @Size( min = 1, max = 200 )
    protected String dishname;

    @NotNull
    @Size( min = 1, max = 300 )
    protected String dishdescription;

    @Size( max = 300 )
    protected String imageurl;

    @NotNull
    protected Long price;


    protected Integer type;


    protected Integer hasspecification;

    @Size( max = 10 )
    protected String defaultggno;


    protected Date startdate;


    protected Date enddate;


    protected Integer notforsale;


    protected Integer paused;


    protected Date createdate;


    protected Date modifydate;

    @Size( max = 50 )
    protected String createuser;

    @Size( max = 50 )
    protected String modifyuser;


    protected Integer status;

    @Size( max = 50 )
    protected String platform;


    protected Date newstatusenddate;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }

    public Long getUid() {
        return this.uid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setCorpid( Long corpid ) {
        this.corpid = corpid;
    }
    public Long getCorpid() {
        return this.corpid;
    }

    public void setNo( String no ) {
        this.no = no;
    }
    public String getNo() {
        return this.no;
    }

    public void setCategoryid( String categoryid ) {
        this.categoryid = categoryid;
    }
    public String getCategoryid() {
        return this.categoryid;
    }

    public void setDishname( String dishname ) {
        this.dishname = dishname;
    }
    public String getDishname() {
        return this.dishname;
    }

    public void setDishdescription( String dishdescription ) {
        this.dishdescription = dishdescription;
    }
    public String getDishdescription() {
        return this.dishdescription;
    }

    public void setImageurl( String imageurl ) {
        this.imageurl = imageurl;
    }
    public String getImageurl() {
        return this.imageurl;
    }

    public void setPrice( Long price ) {
        this.price = price;
    }
    public Long getPrice() {
        return this.price;
    }

    public void setType( Integer type ) {
        this.type = type;
    }
    public Integer getType() {
        return this.type;
    }

    public void setHasspecification( Integer hasspecification ) {
        this.hasspecification = hasspecification;
    }
    public Integer getHasspecification() {
        return this.hasspecification;
    }

    public void setDefaultggno( String defaultggno ) {
        this.defaultggno = defaultggno;
    }
    public String getDefaultggno() {
        return this.defaultggno;
    }

    public void setStartdate( Date startdate ) {
        this.startdate = startdate;
    }
    public Date getStartdate() {
        return this.startdate;
    }

    public void setEnddate( Date enddate ) {
        this.enddate = enddate;
    }
    public Date getEnddate() {
        return this.enddate;
    }

    public void setNotforsale( Integer notforsale ) {
        this.notforsale = notforsale;
    }
    public Integer getNotforsale() {
        return this.notforsale;
    }

    public void setPaused( Integer paused ) {
        this.paused = paused;
    }
    public Integer getPaused() {
        return this.paused;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }

    public void setNewstatusenddate( Date newstatusenddate ) {
        this.newstatusenddate = newstatusenddate;
    }
    public Date getNewstatusenddate() {
        return this.newstatusenddate;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(uid);
        sb.append("|");
        sb.append(corpid);
        sb.append("|");
        sb.append(no);
        sb.append("|");
        sb.append(categoryid);
        sb.append("|");
        sb.append(dishname);
        sb.append("|");
        sb.append(dishdescription);
        sb.append("|");
        sb.append(imageurl);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(hasspecification);
        sb.append("|");
        sb.append(defaultggno);
        sb.append("|");
        sb.append(startdate);
        sb.append("|");
        sb.append(enddate);
        sb.append("|");
        sb.append(notforsale);
        sb.append("|");
        sb.append(paused);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        sb.append("|");
        sb.append(newstatusenddate);
        return sb.toString(); 
    } 


}
