/*
 * Created on 16 五月 2015 ( Time 16:12:44 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model.base;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Orderdetail implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    @Size( min = 1, max = 50 )
    protected String orderno;
    @NotNull
    protected Long uid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    protected Integer no;


    protected Long orderidno;


    protected Double price;


    protected Double priceatsale;


    protected Double amountmoney;


    protected Double amountatsale;


    protected Integer amount;


    protected Byte discountid;


    protected Date createdate;


    protected Date modifydate;

    @Size( max = 50 )
    protected String createuser;

    @Size( max = 50 )
    protected String modifyuser;


    protected Byte delflg;

    @Size( max = 50 )
    protected String platform;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setOrderno( String orderno ) {
        this.orderno = orderno ;
    }

    public String getOrderno() {
        return this.orderno;
    }

    public void setUid( Long uid ) {
        this.uid = uid ;
    }

    public Long getUid() {
        return this.uid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setNo( Integer no ) {
        this.no = no;
    }
    public Integer getNo() {
        return this.no;
    }

    public void setOrderidno( Long orderidno ) {
        this.orderidno = orderidno;
    }
    public Long getOrderidno() {
        return this.orderidno;
    }

    public void setPrice( Double price ) {
        this.price = price;
    }
    public Double getPrice() {
        return this.price;
    }

    public void setPriceatsale( Double priceatsale ) {
        this.priceatsale = priceatsale;
    }
    public Double getPriceatsale() {
        return this.priceatsale;
    }

    public void setAmountmoney( Double amountmoney ) {
        this.amountmoney = amountmoney;
    }
    public Double getAmountmoney() {
        return this.amountmoney;
    }

    public void setAmountatsale( Double amountatsale ) {
        this.amountatsale = amountatsale;
    }
    public Double getAmountatsale() {
        return this.amountatsale;
    }

    public void setAmount( Integer amount ) {
        this.amount = amount;
    }
    public Integer getAmount() {
        return this.amount;
    }

    public void setDiscountid( Byte discountid ) {
        this.discountid = discountid;
    }
    public Byte getDiscountid() {
        return this.discountid;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    public void setDelflg( Byte delflg ) {
        this.delflg = delflg;
    }
    public Byte getDelflg() {
        return this.delflg;
    }

    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(no);
        sb.append("|");
        sb.append(orderidno);
        sb.append("|");
        sb.append(orderno);
        sb.append("|");
        sb.append(uid);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(priceatsale);
        sb.append("|");
        sb.append(amountmoney);
        sb.append("|");
        sb.append(amountatsale);
        sb.append("|");
        sb.append(amount);
        sb.append("|");
        sb.append(discountid);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(delflg);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 


}
