/*
 * Created on 12 五月 2015 ( Time 20:53:01 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dt.hippo.auto.model.Cateringcorpinfo;
import com.dt.hippo.auto.model.jpa.CateringcorpinfoEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class CateringcorpinfoServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public CateringcorpinfoServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'CateringcorpinfoEntity' to 'Cateringcorpinfo'
	 * @param cateringcorpinfoEntity
	 */
	public Cateringcorpinfo mapCateringcorpinfoEntityToCateringcorpinfo(CateringcorpinfoEntity cateringcorpinfoEntity) {
		if(cateringcorpinfoEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Cateringcorpinfo cateringcorpinfo = map(cateringcorpinfoEntity, Cateringcorpinfo.class);

		return cateringcorpinfo;
	}
	
	/**
	 * Mapping from 'Cateringcorpinfo' to 'CateringcorpinfoEntity'
	 * @param cateringcorpinfo
	 * @param cateringcorpinfoEntity
	 */
	public void mapCateringcorpinfoToCateringcorpinfoEntity(Cateringcorpinfo cateringcorpinfo, CateringcorpinfoEntity cateringcorpinfoEntity) {
		if(cateringcorpinfo == null) {
			return;
		}

		//--- Generic mapping 
		map(cateringcorpinfo, cateringcorpinfoEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}