/*
 * Created on 18 五月 2015 ( Time 11:07:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dt.hippo.auto.model.Dishprice;
import com.dt.hippo.auto.model.jpa.DishpriceEntity;
import com.dt.hippo.auto.model.jpa.DishspecificationinfoEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class DishpriceServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public DishpriceServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'DishpriceEntity' to 'Dishprice'
	 * @param dishpriceEntity
	 */
	public Dishprice mapDishpriceEntityToDishprice(DishpriceEntity dishpriceEntity) {
		if(dishpriceEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Dishprice dishprice = map(dishpriceEntity, Dishprice.class);

		//--- Link mapping ( link to Dishspecificationinfo )
		if(dishpriceEntity.getDishspecificationinfo() != null) {
			dishprice.setSpecificationid(dishpriceEntity.getDishspecificationinfo().getUid());
		}
		return dishprice;
	}
	
	/**
	 * Mapping from 'Dishprice' to 'DishpriceEntity'
	 * @param dishprice
	 * @param dishpriceEntity
	 */
	public void mapDishpriceToDishpriceEntity(Dishprice dishprice, DishpriceEntity dishpriceEntity) {
		if(dishprice == null) {
			return;
		}

		//--- Generic mapping 
		map(dishprice, dishpriceEntity);

		//--- Link mapping ( link : dishprice )
		if( hasLinkToDishspecificationinfo(dishprice) ) {
			DishspecificationinfoEntity dishspecificationinfo1 = new DishspecificationinfoEntity();
			dishspecificationinfo1.setUid( dishprice.getSpecificationid() );
			dishpriceEntity.setDishspecificationinfo( dishspecificationinfo1 );
		} else {
			dishpriceEntity.setDishspecificationinfo( null );
		}

	}
	
	/**
	 * Verify that Dishspecificationinfo id is valid.
	 * @param Dishspecificationinfo Dishspecificationinfo
	 * @return boolean
	 */
	private boolean hasLinkToDishspecificationinfo(Dishprice dishprice) {
		if(dishprice.getSpecificationid() != null) {
			return true;
		}
		return false;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}