/*
 * Created on 13 五月 2015 ( Time 21:15:28 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dt.hippo.auto.model.Payment;
import com.dt.hippo.auto.model.jpa.PaymentEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class PaymentServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public PaymentServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'PaymentEntity' to 'Payment'
	 * @param paymentEntity
	 */
	public Payment mapPaymentEntityToPayment(PaymentEntity paymentEntity) {
		if(paymentEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Payment payment = map(paymentEntity, Payment.class);

		return payment;
	}
	
	/**
	 * Mapping from 'Payment' to 'PaymentEntity'
	 * @param payment
	 * @param paymentEntity
	 */
	public void mapPaymentToPaymentEntity(Payment payment, PaymentEntity paymentEntity) {
		if(payment == null) {
			return;
		}

		//--- Generic mapping 
		map(payment, paymentEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}