/*
 * Created on 18 五月 2015 ( Time 11:47:30 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dt.hippo.auto.model.Sequence;
import com.dt.hippo.auto.model.jpa.SequenceEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SequenceServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public SequenceServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'SequenceEntity' to 'Sequence'
	 * @param sequenceEntity
	 */
	public Sequence mapSequenceEntityToSequence(SequenceEntity sequenceEntity) {
		if(sequenceEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Sequence sequence = map(sequenceEntity, Sequence.class);

		return sequence;
	}
	
	/**
	 * Mapping from 'Sequence' to 'SequenceEntity'
	 * @param sequence
	 * @param sequenceEntity
	 */
	public void mapSequenceToSequenceEntity(Sequence sequence, SequenceEntity sequenceEntity) {
		if(sequence == null) {
			return;
		}

		//--- Generic mapping 
		map(sequence, sequenceEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}