/*
 * Created on 18 五月 2015 ( Time 11:07:18 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dt.hippo.auto.model.Systemparameter;
import com.dt.hippo.auto.model.jpa.SystemparameterEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class SystemparameterServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public SystemparameterServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'SystemparameterEntity' to 'Systemparameter'
	 * @param systemparameterEntity
	 */
	public Systemparameter mapSystemparameterEntityToSystemparameter(SystemparameterEntity systemparameterEntity) {
		if(systemparameterEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Systemparameter systemparameter = map(systemparameterEntity, Systemparameter.class);

		return systemparameter;
	}
	
	/**
	 * Mapping from 'Systemparameter' to 'SystemparameterEntity'
	 * @param systemparameter
	 * @param systemparameterEntity
	 */
	public void mapSystemparameterToSystemparameterEntity(Systemparameter systemparameter, SystemparameterEntity systemparameterEntity) {
		if(systemparameter == null) {
			return;
		}

		//--- Generic mapping 
		map(systemparameter, systemparameterEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}