/*
 * Created on 18 五月 2015 ( Time 11:07:18 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service.mapping;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;
import com.dt.hippo.auto.model.Targetlist;
import com.dt.hippo.auto.model.jpa.TargetlistEntity;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TargetlistServiceMapper extends AbstractServiceMapper {

	/**
	 * ModelMapper : bean to bean mapping library.
	 */
	private ModelMapper modelMapper;
	
	/**
	 * Constructor.
	 */
	public TargetlistServiceMapper() {
		modelMapper = new ModelMapper();
		modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
	}

	/**
	 * Mapping from 'TargetlistEntity' to 'Targetlist'
	 * @param targetlistEntity
	 */
	public Targetlist mapTargetlistEntityToTargetlist(TargetlistEntity targetlistEntity) {
		if(targetlistEntity == null) {
			return null;
		}

		//--- Generic mapping 
		Targetlist targetlist = map(targetlistEntity, Targetlist.class);

		return targetlist;
	}
	
	/**
	 * Mapping from 'Targetlist' to 'TargetlistEntity'
	 * @param targetlist
	 * @param targetlistEntity
	 */
	public void mapTargetlistToTargetlistEntity(Targetlist targetlist, TargetlistEntity targetlistEntity) {
		if(targetlist == null) {
			return;
		}

		//--- Generic mapping 
		map(targetlist, targetlistEntity);

	}
	
	/**
	 * {@inheritDoc}
	 */
	@Override
	protected ModelMapper getModelMapper() {
		return modelMapper;
	}

	protected void setModelMapper(ModelMapper modelMapper) {
		this.modelMapper = modelMapper;
	}

}