/*
 * Created on 18 五月 2015 ( Time 17:57:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa.base;

import java.io.Serializable;


//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "comboinfo"
 *
 * @author Telosys Tools Generator
 *
 */
@MappedSuperclass
//@Entity
@Table(name="comboinfo", catalog="hippo" )
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="ComboinfoEntity.countAll", query="SELECT COUNT(x) FROM ComboinfoEntity x" )
//} )
public class ComboinfoEntity extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="uid", nullable=false)
    protected Long       uid          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="dishid")
    protected Long       dishid       ;

    @Column(name="specificationId")
    protected Long       specificationid ;

    @Column(name="corpId")
    protected Long       corpid       ;

    @Column(name="placeholder")
    protected Integer    placeholder  ;

    @Column(name="orderInPlaceholder")
    protected Integer    orderinplaceholder ;

    @Column(name="amount")
    protected Integer    amount       ;

    @Column(name="priceDifference")
    protected Long       pricedifference ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
    protected Date       createdate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
    protected Date       modifydate   ;

    @Column(name="createUser", length=50)
    protected String     createuser   ;

    @Column(name="modifyUser", length=50)
    protected String     modifyuser   ;

    @Column(name="status")
    protected Integer    status       ;

    @Column(name="platform", length=50)
    protected String     platform     ;

	// "specificationid" (column "specificationId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ComboinfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }
    public Long getUid() {
        return this.uid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : dishid ( BIGINT ) 
    public void setDishid( Long dishid ) {
        this.dishid = dishid;
    }
    public Long getDishid() {
        return this.dishid;
    }

    //--- DATABASE MAPPING : specificationId ( BIGINT ) 
    public void setSpecificationid( Long specificationid ) {
        this.specificationid = specificationid;
    }
    public Long getSpecificationid() {
        return this.specificationid;
    }

    //--- DATABASE MAPPING : corpId ( BIGINT ) 
    public void setCorpid( Long corpid ) {
        this.corpid = corpid;
    }
    public Long getCorpid() {
        return this.corpid;
    }

    //--- DATABASE MAPPING : placeholder ( INT ) 
    public void setPlaceholder( Integer placeholder ) {
        this.placeholder = placeholder;
    }
    public Integer getPlaceholder() {
        return this.placeholder;
    }

    //--- DATABASE MAPPING : orderInPlaceholder ( INT ) 
    public void setOrderinplaceholder( Integer orderinplaceholder ) {
        this.orderinplaceholder = orderinplaceholder;
    }
    public Integer getOrderinplaceholder() {
        return this.orderinplaceholder;
    }

    //--- DATABASE MAPPING : amount ( INT ) 
    public void setAmount( Integer amount ) {
        this.amount = amount;
    }
    public Integer getAmount() {
        return this.amount;
    }

    //--- DATABASE MAPPING : priceDifference ( BIGINT ) 
    public void setPricedifference( Long pricedifference ) {
        this.pricedifference = pricedifference;
    }
    public Long getPricedifference() {
        return this.pricedifference;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uid);
        sb.append("]:"); 
        sb.append(dishid);
        sb.append("|");
        sb.append(specificationid);
        sb.append("|");
        sb.append(corpid);
        sb.append("|");
        sb.append(placeholder);
        sb.append("|");
        sb.append(orderinplaceholder);
        sb.append("|");
        sb.append(amount);
        sb.append("|");
        sb.append(pricedifference);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 

}
