/*
 * Created on 27 五月 2015 ( Time 17:36:24 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa.base;

import java.io.Serializable;


//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "dishinfo"
 *
 * @author Telosys Tools Generator
 *
 */
@MappedSuperclass
//@Entity
@Table(name="dishinfo", catalog="hippo" )
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="DishinfoEntity.countAll", query="SELECT COUNT(x) FROM DishinfoEntity x" )
//} )
public class DishinfoEntity extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    protected Long       uid          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    protected Long       corpid       ;

    protected String     no           ;

    protected String     categoryid   ;

    protected String     dishname     ;

    protected String     dishdescription ;

    protected String     imageurl     ;

    protected Long       price        ;

    protected Integer    type         ;

    protected Integer    hasspecification ;

    protected String     defaultggno  ;

    protected Date       startdate    ;

    protected Date       enddate      ;

    protected Integer    notforsale   ;

    protected Integer    paused       ;

    protected Date       createdate   ;

    protected Date       modifydate   ;

    protected String     createuser   ;

    protected String     modifyuser   ;

    protected Integer    status       ;

    protected String     platform     ;

    protected Date       newstatusenddate ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DishinfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }
       @Id
    @Column(name="uid", nullable=false)
  public Long getUid() {
        return this.uid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : corpId ( BIGINT ) 
    public void setCorpid( Long corpid ) {
        this.corpid = corpid;
    }
       @Column(name="corpId")
 public Long getCorpid() {
        return this.corpid;
    }

    //--- DATABASE MAPPING : no ( VARCHAR ) 
    public void setNo( String no ) {
        this.no = no;
    }
       @Column(name="no", length=10)
 public String getNo() {
        return this.no;
    }

    //--- DATABASE MAPPING : categoryId ( VARCHAR ) 
    public void setCategoryid( String categoryid ) {
        this.categoryid = categoryid;
    }
       @Column(name="categoryId", nullable=false, length=5)
 public String getCategoryid() {
        return this.categoryid;
    }

    //--- DATABASE MAPPING : dishName ( VARCHAR ) 
    public void setDishname( String dishname ) {
        this.dishname = dishname;
    }
       @Column(name="dishName", nullable=false, length=200)
 public String getDishname() {
        return this.dishname;
    }

    //--- DATABASE MAPPING : dishDescription ( VARCHAR ) 
    public void setDishdescription( String dishdescription ) {
        this.dishdescription = dishdescription;
    }
       @Column(name="dishDescription", nullable=false, length=300)
 public String getDishdescription() {
        return this.dishdescription;
    }

    //--- DATABASE MAPPING : imageUrl ( VARCHAR ) 
    public void setImageurl( String imageurl ) {
        this.imageurl = imageurl;
    }
       @Column(name="imageUrl", length=300)
 public String getImageurl() {
        return this.imageurl;
    }

    //--- DATABASE MAPPING : price ( BIGINT ) 
    public void setPrice( Long price ) {
        this.price = price;
    }
       @Column(name="price", nullable=false)
 public Long getPrice() {
        return this.price;
    }

    //--- DATABASE MAPPING : type ( INT ) 
    public void setType( Integer type ) {
        this.type = type;
    }
       @Column(name="type")
 public Integer getType() {
        return this.type;
    }

    //--- DATABASE MAPPING : hasSpecification ( INT ) 
    public void setHasspecification( Integer hasspecification ) {
        this.hasspecification = hasspecification;
    }
       @Column(name="hasSpecification")
 public Integer getHasspecification() {
        return this.hasspecification;
    }

    //--- DATABASE MAPPING : defaultGgno ( VARCHAR ) 
    public void setDefaultggno( String defaultggno ) {
        this.defaultggno = defaultggno;
    }
       @Column(name="defaultGgno", length=10)
 public String getDefaultggno() {
        return this.defaultggno;
    }

    //--- DATABASE MAPPING : startDate ( DATE ) 
    public void setStartdate( Date startdate ) {
        this.startdate = startdate;
    }
       @Temporal(TemporalType.DATE)
    @Column(name="startDate")
 public Date getStartdate() {
        return this.startdate;
    }

    //--- DATABASE MAPPING : endDate ( DATE ) 
    public void setEnddate( Date enddate ) {
        this.enddate = enddate;
    }
       @Temporal(TemporalType.DATE)
    @Column(name="endDate")
 public Date getEnddate() {
        return this.enddate;
    }

    //--- DATABASE MAPPING : notForSale ( INT ) 
    public void setNotforsale( Integer notforsale ) {
        this.notforsale = notforsale;
    }
       @Column(name="notForSale")
 public Integer getNotforsale() {
        return this.notforsale;
    }

    //--- DATABASE MAPPING : paused ( INT ) 
    public void setPaused( Integer paused ) {
        this.paused = paused;
    }
       @Column(name="paused")
 public Integer getPaused() {
        return this.paused;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
 public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
 public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
       @Column(name="createUser", length=50)
 public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
       @Column(name="modifyUser", length=50)
 public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
       @Column(name="status")
 public Integer getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
       @Column(name="platform", length=50)
 public String getPlatform() {
        return this.platform;
    }

    //--- DATABASE MAPPING : newStatusEndDate ( DATE ) 
    public void setNewstatusenddate( Date newstatusenddate ) {
        this.newstatusenddate = newstatusenddate;
    }
       @Temporal(TemporalType.DATE)
    @Column(name="newStatusEndDate")
 public Date getNewstatusenddate() {
        return this.newstatusenddate;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uid);
        sb.append("]:"); 
        sb.append(corpid);
        sb.append("|");
        sb.append(no);
        sb.append("|");
        sb.append(categoryid);
        sb.append("|");
        sb.append(dishname);
        sb.append("|");
        sb.append(dishdescription);
        sb.append("|");
        sb.append(imageurl);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(hasspecification);
        sb.append("|");
        sb.append(defaultggno);
        sb.append("|");
        sb.append(startdate);
        sb.append("|");
        sb.append(enddate);
        sb.append("|");
        sb.append(notforsale);
        sb.append("|");
        sb.append(paused);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        sb.append("|");
        sb.append(newstatusenddate);
        return sb.toString(); 
    } 

}
