/*
 * Created on 27 五月 2015 ( Time 17:36:24 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa.base;

import java.io.Serializable;


//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "dishSpecificationInfo"
 *
 * @author Telosys Tools Generator
 *
 */
@MappedSuperclass
//@Entity
@Table(name="dishSpecificationInfo", catalog="hippo" )
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="DishspecificationinfoEntity.countAll", query="SELECT COUNT(x) FROM DishspecificationinfoEntity x" )
//} )
public class DishspecificationinfoEntity extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    protected Long       uid          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    protected Long       dishid       ;

    protected String     ggno         ;

    protected String     name         ;

    protected Long       corpid       ;

    protected String     dishname     ;

    protected String     dishdescription ;

    protected String     imageurl     ;

    protected Long       price        ;

    protected Integer    orderindex   ;

    protected Date       createdate   ;

    protected Date       modifydate   ;

    protected String     createuser   ;

    protected String     modifyuser   ;

    protected Integer    status       ;

    protected String     platform     ;

	// "dishid" (column "dishId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DishspecificationinfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }
       @Id
    @Column(name="uid", nullable=false)
  public Long getUid() {
        return this.uid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : dishId ( BIGINT ) 
    public void setDishid( Long dishid ) {
        this.dishid = dishid;
    }
       @Column(name="dishId")
 public Long getDishid() {
        return this.dishid;
    }

    //--- DATABASE MAPPING : ggno ( VARCHAR ) 
    public void setGgno( String ggno ) {
        this.ggno = ggno;
    }
       @Column(name="ggno", length=10)
 public String getGgno() {
        return this.ggno;
    }

    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
       @Column(name="name", length=50)
 public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : corpId ( BIGINT ) 
    public void setCorpid( Long corpid ) {
        this.corpid = corpid;
    }
       @Column(name="corpId", nullable=false)
 public Long getCorpid() {
        return this.corpid;
    }

    //--- DATABASE MAPPING : dishName ( VARCHAR ) 
    public void setDishname( String dishname ) {
        this.dishname = dishname;
    }
       @Column(name="dishName", length=200)
 public String getDishname() {
        return this.dishname;
    }

    //--- DATABASE MAPPING : dishDescription ( VARCHAR ) 
    public void setDishdescription( String dishdescription ) {
        this.dishdescription = dishdescription;
    }
       @Column(name="dishDescription", length=300)
 public String getDishdescription() {
        return this.dishdescription;
    }

    //--- DATABASE MAPPING : imageUrl ( VARCHAR ) 
    public void setImageurl( String imageurl ) {
        this.imageurl = imageurl;
    }
       @Column(name="imageUrl", length=300)
 public String getImageurl() {
        return this.imageurl;
    }

    //--- DATABASE MAPPING : price ( BIGINT ) 
    public void setPrice( Long price ) {
        this.price = price;
    }
       @Column(name="price", nullable=false)
 public Long getPrice() {
        return this.price;
    }

    //--- DATABASE MAPPING : orderIndex ( INT ) 
    public void setOrderindex( Integer orderindex ) {
        this.orderindex = orderindex;
    }
       @Column(name="orderIndex")
 public Integer getOrderindex() {
        return this.orderindex;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
 public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
 public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
       @Column(name="createUser", length=50)
 public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
       @Column(name="modifyUser", length=50)
 public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
       @Column(name="status")
 public Integer getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
       @Column(name="platform", length=50)
 public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uid);
        sb.append("]:"); 
        sb.append(dishid);
        sb.append("|");
        sb.append(ggno);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(corpid);
        sb.append("|");
        sb.append(dishname);
        sb.append("|");
        sb.append(dishdescription);
        sb.append("|");
        sb.append(imageurl);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(orderindex);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 

}
