/*
 * Created on 16 五月 2015 ( Time 16:13:12 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a composite Primary Key  

package com.dt.hippo.auto.model.jpa.base;

import java.io.Serializable;

import com.dt.hippo.auto.model.jpa.OrderdetailEntityKey;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "orderdetail"
 *
 * @author Telosys Tools Generator
 *
 */
@MappedSuperclass
//@Entity
@Table(name="orderdetail", catalog="hippo" )
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="OrderdetailEntity.countAll", query="SELECT COUNT(x) FROM OrderdetailEntity x" )
//} )
public class OrderdetailEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )  
    //----------------------------------------------------------------------
	@EmbeddedId
    protected OrderdetailEntityKey compositePrimaryKey ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="no")
    protected Integer    no           ;

    @Column(name="orderIdNo")
    protected Long       orderidno    ;

    @Column(name="price")
    protected Double     price        ;

    @Column(name="priceAtSale")
    protected Double     priceatsale  ;

    @Column(name="amountMoney")
    protected Double     amountmoney  ;

    @Column(name="amountAtSale")
    protected Double     amountatsale ;

    @Column(name="amount")
    protected Integer    amount       ;

    @Column(name="discountId")
    protected Byte       discountid   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
    protected Date       createdate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
    protected Date       modifydate   ;

    @Column(name="createUser", length=50)
    protected String     createuser   ;

    @Column(name="modifyUser", length=50)
    protected String     modifyuser   ;

    @Column(name="delFlg")
    protected Byte       delflg       ;

    @Column(name="platform", length=50)
    protected String     platform     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public OrderdetailEntity() {
		super();
		this.compositePrimaryKey = new OrderdetailEntityKey();       
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY 
    //----------------------------------------------------------------------
    public void setOrderno( String orderno ) {
        this.compositePrimaryKey.setOrderno( orderno ) ;
    }
    public String getOrderno() {
        return this.compositePrimaryKey.getOrderno() ;
    }
    public void setUid( Long uid ) {
        this.compositePrimaryKey.setUid( uid ) ;
    }
    public Long getUid() {
        return this.compositePrimaryKey.getUid() ;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : no ( INT ) 
    public void setNo( Integer no ) {
        this.no = no;
    }
    public Integer getNo() {
        return this.no;
    }

    //--- DATABASE MAPPING : orderIdNo ( BIGINT ) 
    public void setOrderidno( Long orderidno ) {
        this.orderidno = orderidno;
    }
    public Long getOrderidno() {
        return this.orderidno;
    }

    //--- DATABASE MAPPING : price ( DOUBLE ) 
    public void setPrice( Double price ) {
        this.price = price;
    }
    public Double getPrice() {
        return this.price;
    }

    //--- DATABASE MAPPING : priceAtSale ( DOUBLE ) 
    public void setPriceatsale( Double priceatsale ) {
        this.priceatsale = priceatsale;
    }
    public Double getPriceatsale() {
        return this.priceatsale;
    }

    //--- DATABASE MAPPING : amountMoney ( DOUBLE ) 
    public void setAmountmoney( Double amountmoney ) {
        this.amountmoney = amountmoney;
    }
    public Double getAmountmoney() {
        return this.amountmoney;
    }

    //--- DATABASE MAPPING : amountAtSale ( DOUBLE ) 
    public void setAmountatsale( Double amountatsale ) {
        this.amountatsale = amountatsale;
    }
    public Double getAmountatsale() {
        return this.amountatsale;
    }

    //--- DATABASE MAPPING : amount ( INT ) 
    public void setAmount( Integer amount ) {
        this.amount = amount;
    }
    public Integer getAmount() {
        return this.amount;
    }

    //--- DATABASE MAPPING : discountId ( TINYINT ) 
    public void setDiscountid( Byte discountid ) {
        this.discountid = discountid;
    }
    public Byte getDiscountid() {
        return this.discountid;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : delFlg ( TINYINT ) 
    public void setDelflg( Byte delflg ) {
        this.delflg = delflg;
    }
    public Byte getDelflg() {
        return this.delflg;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        if ( compositePrimaryKey != null ) {  
            sb.append(compositePrimaryKey.toString());  
        }  
        else {  
            sb.append( "(null-key)" ); 
        }  
        sb.append("]:"); 
        sb.append(no);
        sb.append("|");
        sb.append(orderidno);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(priceatsale);
        sb.append("|");
        sb.append(amountmoney);
        sb.append("|");
        sb.append(amountatsale);
        sb.append("|");
        sb.append(amount);
        sb.append("|");
        sb.append(discountid);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(delflg);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 

}
