/*
 * Created on 28 五月 2015 ( Time 11:34:53 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa.base;

import java.io.Serializable;


//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "orderheader"
 *
 * @author Telosys Tools Generator
 *
 */
@MappedSuperclass
//@Entity
@Table(name="orderheader", catalog="hippo" )
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="OrderheaderEntity.countAll", query="SELECT COUNT(x) FROM OrderheaderEntity x" )
//} )
public class OrderheaderEntity extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    protected Long       uid          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    protected String     orderno      ;

    protected Long       corpid       ;

    protected Long       parentuid    ;

    protected String     parentorderno ;

    protected String     paymentno    ;

    protected Long       realpaymentamount ;

    protected Long       paymentamount ;

    protected Integer    orderstatus  ;

    protected String     orderinfo    ;

    protected Integer    paymentmethod ;

    protected Date       tradedate    ;

    protected String     useragent    ;

    protected Long       userid       ;

    protected Long       storeid      ;

    protected Date       delievertime ;

    protected Date       canceltime   ;

    protected Date       confirmtime  ;

    protected String     ip           ;

    protected Date       createdate   ;

    protected Date       modifydate   ;

    protected String     createuser   ;

    protected String     modifyuser   ;

    protected Integer    status       ;

    protected String     platform     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public OrderheaderEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }
       @Id
    @Column(name="uid", nullable=false)
  public Long getUid() {
        return this.uid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : orderNo ( VARCHAR ) 
    public void setOrderno( String orderno ) {
        this.orderno = orderno;
    }
       @Column(name="orderNo", length=50)
 public String getOrderno() {
        return this.orderno;
    }

    //--- DATABASE MAPPING : corpId ( BIGINT ) 
    public void setCorpid( Long corpid ) {
        this.corpid = corpid;
    }
       @Column(name="corpId")
 public Long getCorpid() {
        return this.corpid;
    }

    //--- DATABASE MAPPING : parentUid ( BIGINT ) 
    public void setParentuid( Long parentuid ) {
        this.parentuid = parentuid;
    }
       @Column(name="parentUid")
 public Long getParentuid() {
        return this.parentuid;
    }

    //--- DATABASE MAPPING : parentOrderNo ( VARCHAR ) 
    public void setParentorderno( String parentorderno ) {
        this.parentorderno = parentorderno;
    }
       @Column(name="parentOrderNo", length=50)
 public String getParentorderno() {
        return this.parentorderno;
    }

    //--- DATABASE MAPPING : paymentNo ( VARCHAR ) 
    public void setPaymentno( String paymentno ) {
        this.paymentno = paymentno;
    }
       @Column(name="paymentNo", length=50)
 public String getPaymentno() {
        return this.paymentno;
    }

    //--- DATABASE MAPPING : realPaymentAmount ( BIGINT ) 
    public void setRealpaymentamount( Long realpaymentamount ) {
        this.realpaymentamount = realpaymentamount;
    }
       @Column(name="realPaymentAmount")
 public Long getRealpaymentamount() {
        return this.realpaymentamount;
    }

    //--- DATABASE MAPPING : paymentamount ( BIGINT ) 
    public void setPaymentamount( Long paymentamount ) {
        this.paymentamount = paymentamount;
    }
       @Column(name="paymentamount")
 public Long getPaymentamount() {
        return this.paymentamount;
    }

    //--- DATABASE MAPPING : orderStatus ( INT ) 
    public void setOrderstatus( Integer orderstatus ) {
        this.orderstatus = orderstatus;
    }
       @Column(name="orderStatus")
 public Integer getOrderstatus() {
        return this.orderstatus;
    }

    //--- DATABASE MAPPING : orderInfo ( VARCHAR ) 
    public void setOrderinfo( String orderinfo ) {
        this.orderinfo = orderinfo;
    }
       @Column(name="orderInfo", length=500)
 public String getOrderinfo() {
        return this.orderinfo;
    }

    //--- DATABASE MAPPING : paymentMethod ( INT ) 
    public void setPaymentmethod( Integer paymentmethod ) {
        this.paymentmethod = paymentmethod;
    }
       @Column(name="paymentMethod")
 public Integer getPaymentmethod() {
        return this.paymentmethod;
    }

    //--- DATABASE MAPPING : tradeDate ( DATETIME ) 
    public void setTradedate( Date tradedate ) {
        this.tradedate = tradedate;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="tradeDate")
 public Date getTradedate() {
        return this.tradedate;
    }

    //--- DATABASE MAPPING : useragent ( VARCHAR ) 
    public void setUseragent( String useragent ) {
        this.useragent = useragent;
    }
       @Column(name="useragent", length=500)
 public String getUseragent() {
        return this.useragent;
    }

    //--- DATABASE MAPPING : userId ( BIGINT ) 
    public void setUserid( Long userid ) {
        this.userid = userid;
    }
       @Column(name="userId")
 public Long getUserid() {
        return this.userid;
    }

    //--- DATABASE MAPPING : storeId ( BIGINT ) 
    public void setStoreid( Long storeid ) {
        this.storeid = storeid;
    }
       @Column(name="storeId")
 public Long getStoreid() {
        return this.storeid;
    }

    //--- DATABASE MAPPING : delieverTime ( DATETIME ) 
    public void setDelievertime( Date delievertime ) {
        this.delievertime = delievertime;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="delieverTime")
 public Date getDelievertime() {
        return this.delievertime;
    }

    //--- DATABASE MAPPING : cancelTime ( DATETIME ) 
    public void setCanceltime( Date canceltime ) {
        this.canceltime = canceltime;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="cancelTime")
 public Date getCanceltime() {
        return this.canceltime;
    }

    //--- DATABASE MAPPING : confirmTime ( DATETIME ) 
    public void setConfirmtime( Date confirmtime ) {
        this.confirmtime = confirmtime;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="confirmTime")
 public Date getConfirmtime() {
        return this.confirmtime;
    }

    //--- DATABASE MAPPING : ip ( VARCHAR ) 
    public void setIp( String ip ) {
        this.ip = ip;
    }
       @Column(name="ip", length=20)
 public String getIp() {
        return this.ip;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
 public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
       @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
 public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
       @Column(name="createUser", length=50)
 public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
       @Column(name="modifyUser", length=50)
 public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
       @Column(name="status")
 public Integer getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
       @Column(name="platform", length=50)
 public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uid);
        sb.append("]:"); 
        sb.append(orderno);
        sb.append("|");
        sb.append(corpid);
        sb.append("|");
        sb.append(parentuid);
        sb.append("|");
        sb.append(parentorderno);
        sb.append("|");
        sb.append(paymentno);
        sb.append("|");
        sb.append(realpaymentamount);
        sb.append("|");
        sb.append(paymentamount);
        sb.append("|");
        sb.append(orderstatus);
        sb.append("|");
        sb.append(orderinfo);
        sb.append("|");
        sb.append(paymentmethod);
        sb.append("|");
        sb.append(tradedate);
        sb.append("|");
        sb.append(useragent);
        sb.append("|");
        sb.append(userid);
        sb.append("|");
        sb.append(storeid);
        sb.append("|");
        sb.append(delievertime);
        sb.append("|");
        sb.append(canceltime);
        sb.append("|");
        sb.append(confirmtime);
        sb.append("|");
        sb.append(ip);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 

}
