/*
 * Created on 18 五月 2015 ( Time 17:57:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa.base;

import java.io.Serializable;


//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "promotionInfo"
 *
 * @author Telosys Tools Generator
 *
 */
@MappedSuperclass
//@Entity
@Table(name="promotionInfo", catalog="hippo" )
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="PromotioninfoEntity.countAll", query="SELECT COUNT(x) FROM PromotioninfoEntity x" )
//} )
public class PromotioninfoEntity extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="uid", nullable=false)
    protected Long       uid          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="corpId")
    protected Long       corpid       ;

    @Column(name="name", nullable=false, length=50)
    protected String     name         ;

    @Column(name="type")
    protected Integer    type         ;

    @Column(name="description", nullable=false, length=300)
    protected String     description  ;

    @Column(name="imageUrl", length=300)
    protected String     imageurl     ;

    @Column(name="discount")
    protected Integer    discount     ;

    @Column(name="targetCategoryList", length=100)
    protected String     targetcategorylist ;

    @Temporal(TemporalType.DATE)
    @Column(name="promotionStartDate", nullable=false)
    protected Date       promotionstartdate ;

    @Temporal(TemporalType.DATE)
    @Column(name="promotionEndDate")
    protected Date       promotionenddate ;

    @Column(name="promotionStartTime")
    protected Integer    promotionstarttime ;

    @Column(name="promotionEndTime")
    protected Integer    promotionendtime ;

    @Column(name="storeType")
    protected Integer    storetype    ;

    @Column(name="applyToAll", nullable=false)
    protected Integer    applytoall   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
    protected Date       createdate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
    protected Date       modifydate   ;

    @Column(name="createUser", length=50)
    protected String     createuser   ;

    @Column(name="modifyUser", length=50)
    protected String     modifyuser   ;

    @Column(name="status")
    protected Integer    status       ;

    @Column(name="platform", length=50)
    protected String     platform     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public PromotioninfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }
    public Long getUid() {
        return this.uid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : corpId ( BIGINT ) 
    public void setCorpid( Long corpid ) {
        this.corpid = corpid;
    }
    public Long getCorpid() {
        return this.corpid;
    }

    //--- DATABASE MAPPING : name ( VARCHAR ) 
    public void setName( String name ) {
        this.name = name;
    }
    public String getName() {
        return this.name;
    }

    //--- DATABASE MAPPING : type ( INT ) 
    public void setType( Integer type ) {
        this.type = type;
    }
    public Integer getType() {
        return this.type;
    }

    //--- DATABASE MAPPING : description ( VARCHAR ) 
    public void setDescription( String description ) {
        this.description = description;
    }
    public String getDescription() {
        return this.description;
    }

    //--- DATABASE MAPPING : imageUrl ( VARCHAR ) 
    public void setImageurl( String imageurl ) {
        this.imageurl = imageurl;
    }
    public String getImageurl() {
        return this.imageurl;
    }

    //--- DATABASE MAPPING : discount ( INT ) 
    public void setDiscount( Integer discount ) {
        this.discount = discount;
    }
    public Integer getDiscount() {
        return this.discount;
    }

    //--- DATABASE MAPPING : targetCategoryList ( VARCHAR ) 
    public void setTargetcategorylist( String targetcategorylist ) {
        this.targetcategorylist = targetcategorylist;
    }
    public String getTargetcategorylist() {
        return this.targetcategorylist;
    }

    //--- DATABASE MAPPING : promotionStartDate ( DATE ) 
    public void setPromotionstartdate( Date promotionstartdate ) {
        this.promotionstartdate = promotionstartdate;
    }
    public Date getPromotionstartdate() {
        return this.promotionstartdate;
    }

    //--- DATABASE MAPPING : promotionEndDate ( DATE ) 
    public void setPromotionenddate( Date promotionenddate ) {
        this.promotionenddate = promotionenddate;
    }
    public Date getPromotionenddate() {
        return this.promotionenddate;
    }

    //--- DATABASE MAPPING : promotionStartTime ( INT ) 
    public void setPromotionstarttime( Integer promotionstarttime ) {
        this.promotionstarttime = promotionstarttime;
    }
    public Integer getPromotionstarttime() {
        return this.promotionstarttime;
    }

    //--- DATABASE MAPPING : promotionEndTime ( INT ) 
    public void setPromotionendtime( Integer promotionendtime ) {
        this.promotionendtime = promotionendtime;
    }
    public Integer getPromotionendtime() {
        return this.promotionendtime;
    }

    //--- DATABASE MAPPING : storeType ( INT ) 
    public void setStoretype( Integer storetype ) {
        this.storetype = storetype;
    }
    public Integer getStoretype() {
        return this.storetype;
    }

    //--- DATABASE MAPPING : applyToAll ( INT ) 
    public void setApplytoall( Integer applytoall ) {
        this.applytoall = applytoall;
    }
    public Integer getApplytoall() {
        return this.applytoall;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uid);
        sb.append("]:"); 
        sb.append(corpid);
        sb.append("|");
        sb.append(name);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(description);
        sb.append("|");
        sb.append(imageurl);
        sb.append("|");
        sb.append(discount);
        sb.append("|");
        sb.append(targetcategorylist);
        sb.append("|");
        sb.append(promotionstartdate);
        sb.append("|");
        sb.append(promotionenddate);
        sb.append("|");
        sb.append(promotionstarttime);
        sb.append("|");
        sb.append(promotionendtime);
        sb.append("|");
        sb.append(storetype);
        sb.append("|");
        sb.append(applytoall);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 

}
