/*
 * Created on 18 五月 2015 ( Time 17:57:12 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa.base;

import java.io.Serializable;


//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "storeinfo"
 *
 * @author Telosys Tools Generator
 *
 */
@MappedSuperclass
//@Entity
@Table(name="storeinfo", catalog="hippo" )
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="StoreinfoEntity.countAll", query="SELECT COUNT(x) FROM StoreinfoEntity x" )
//} )
public class StoreinfoEntity extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="uid", nullable=false)
    protected Long       uid          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="corpId")
    protected Long       corpid       ;

    @Column(name="storeNo", length=32)
    protected String     storeno      ;

    @Column(name="storeName", nullable=false, length=200)
    protected String     storename    ;

    @Column(name="storeDescription", length=1000)
    protected String     storedescription ;

    @Column(name="cityId", nullable=false, length=20)
    protected String     cityid       ;

    @Column(name="address", nullable=false, length=400)
    protected String     address      ;

    @Column(name="phone", length=50)
    protected String     phone        ;

    @Column(name="type")
    protected Integer    type         ;

    @Column(name="lng")
    protected Double     lng          ;

    @Column(name="lat")
    protected Double     lat          ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
    protected Date       createdate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
    protected Date       modifydate   ;

    @Column(name="createUser", length=50)
    protected String     createuser   ;

    @Column(name="modifyUser", length=50)
    protected String     modifyuser   ;

    @Column(name="status")
    protected Integer    status       ;

    @Column(name="platform", length=50)
    protected String     platform     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public StoreinfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }
    public Long getUid() {
        return this.uid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : corpId ( BIGINT ) 
    public void setCorpid( Long corpid ) {
        this.corpid = corpid;
    }
    public Long getCorpid() {
        return this.corpid;
    }

    //--- DATABASE MAPPING : storeNo ( VARCHAR ) 
    public void setStoreno( String storeno ) {
        this.storeno = storeno;
    }
    public String getStoreno() {
        return this.storeno;
    }

    //--- DATABASE MAPPING : storeName ( VARCHAR ) 
    public void setStorename( String storename ) {
        this.storename = storename;
    }
    public String getStorename() {
        return this.storename;
    }

    //--- DATABASE MAPPING : storeDescription ( VARCHAR ) 
    public void setStoredescription( String storedescription ) {
        this.storedescription = storedescription;
    }
    public String getStoredescription() {
        return this.storedescription;
    }

    //--- DATABASE MAPPING : cityId ( VARCHAR ) 
    public void setCityid( String cityid ) {
        this.cityid = cityid;
    }
    public String getCityid() {
        return this.cityid;
    }

    //--- DATABASE MAPPING : address ( VARCHAR ) 
    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    //--- DATABASE MAPPING : phone ( VARCHAR ) 
    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    //--- DATABASE MAPPING : type ( INT ) 
    public void setType( Integer type ) {
        this.type = type;
    }
    public Integer getType() {
        return this.type;
    }

    //--- DATABASE MAPPING : lng ( DOUBLE ) 
    public void setLng( Double lng ) {
        this.lng = lng;
    }
    public Double getLng() {
        return this.lng;
    }

    //--- DATABASE MAPPING : lat ( DOUBLE ) 
    public void setLat( Double lat ) {
        this.lat = lat;
    }
    public Double getLat() {
        return this.lat;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uid);
        sb.append("]:"); 
        sb.append(corpid);
        sb.append("|");
        sb.append(storeno);
        sb.append("|");
        sb.append(storename);
        sb.append("|");
        sb.append(storedescription);
        sb.append("|");
        sb.append(cityid);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(lng);
        sb.append("|");
        sb.append(lat);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 

}
