/*
 * Created on 18 五月 2015 ( Time 17:57:12 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa.base;

import java.io.Serializable;


//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "voucherGeneratorInfo"
 *
 * @author Telosys Tools Generator
 *
 */
@MappedSuperclass
//@Entity
@Table(name="voucherGeneratorInfo", catalog="hippo" )
// Define named queries here
//@NamedQueries ( {
//  @NamedQuery ( name="VouchergeneratorinfoEntity.countAll", query="SELECT COUNT(x) FROM VouchergeneratorinfoEntity x" )
//} )
public class VouchergeneratorinfoEntity extends com.dt.hippo.core.base.BaseBeanCommon implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @Column(name="uid", nullable=false)
    protected Integer    uid          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="corpId")
    protected Integer    corpid       ;

    @Column(name="type", nullable=false)
    protected Integer    type         ;

    @Column(name="objectToSend")
    protected Long       objecttosend ;

    @Temporal(TemporalType.DATE)
    @Column(name="deliveryStartDate")
    protected Date       deliverystartdate ;

    @Temporal(TemporalType.DATE)
    @Column(name="deliveryEndDate")
    protected Date       deliveryenddate ;

    @Column(name="deliveryStartTime")
    protected Integer    deliverystarttime ;

    @Column(name="deliveryEndTime")
    protected Integer    deliveryendtime ;

    @Temporal(TemporalType.DATE)
    @Column(name="applyStartDate")
    protected Date       applystartdate ;

    @Temporal(TemporalType.DATE)
    @Column(name="applyEndDate")
    protected Date       applyenddate ;

    @Column(name="limitationMethod")
    protected Integer    limitationmethod ;

    @Column(name="timezone", length=10)
    protected String     timezone     ;

    @Column(name="maxAmount")
    protected Integer    maxamount    ;

    @Column(name="maxAmountPerPerson")
    protected Integer    maxamountperperson ;

    @Column(name="applyToAllStore", nullable=false)
    protected Integer    applytoallstore ;

    @Column(name="applyToAllDish", nullable=false)
    protected Integer    applytoalldish ;

    @Column(name="overlayUse")
    protected Integer    overlayuse   ;

    @Column(name="value")
    protected Integer    value        ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
    protected Date       createdate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
    protected Date       modifydate   ;

    @Column(name="createUser", length=50)
    protected String     createuser   ;

    @Column(name="modifyUser", length=50)
    protected String     modifyuser   ;

    @Column(name="status")
    protected Integer    status       ;

    @Column(name="platform", length=50)
    protected String     platform     ;



    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public VouchergeneratorinfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Integer uid ) {
        this.uid = uid ;
    }
    public Integer getUid() {
        return this.uid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : corpId ( INT ) 
    public void setCorpid( Integer corpid ) {
        this.corpid = corpid;
    }
    public Integer getCorpid() {
        return this.corpid;
    }

    //--- DATABASE MAPPING : type ( INT ) 
    public void setType( Integer type ) {
        this.type = type;
    }
    public Integer getType() {
        return this.type;
    }

    //--- DATABASE MAPPING : objectToSend ( BIGINT ) 
    public void setObjecttosend( Long objecttosend ) {
        this.objecttosend = objecttosend;
    }
    public Long getObjecttosend() {
        return this.objecttosend;
    }

    //--- DATABASE MAPPING : deliveryStartDate ( DATE ) 
    public void setDeliverystartdate( Date deliverystartdate ) {
        this.deliverystartdate = deliverystartdate;
    }
    public Date getDeliverystartdate() {
        return this.deliverystartdate;
    }

    //--- DATABASE MAPPING : deliveryEndDate ( DATE ) 
    public void setDeliveryenddate( Date deliveryenddate ) {
        this.deliveryenddate = deliveryenddate;
    }
    public Date getDeliveryenddate() {
        return this.deliveryenddate;
    }

    //--- DATABASE MAPPING : deliveryStartTime ( INT ) 
    public void setDeliverystarttime( Integer deliverystarttime ) {
        this.deliverystarttime = deliverystarttime;
    }
    public Integer getDeliverystarttime() {
        return this.deliverystarttime;
    }

    //--- DATABASE MAPPING : deliveryEndTime ( INT ) 
    public void setDeliveryendtime( Integer deliveryendtime ) {
        this.deliveryendtime = deliveryendtime;
    }
    public Integer getDeliveryendtime() {
        return this.deliveryendtime;
    }

    //--- DATABASE MAPPING : applyStartDate ( DATE ) 
    public void setApplystartdate( Date applystartdate ) {
        this.applystartdate = applystartdate;
    }
    public Date getApplystartdate() {
        return this.applystartdate;
    }

    //--- DATABASE MAPPING : applyEndDate ( DATE ) 
    public void setApplyenddate( Date applyenddate ) {
        this.applyenddate = applyenddate;
    }
    public Date getApplyenddate() {
        return this.applyenddate;
    }

    //--- DATABASE MAPPING : limitationMethod ( INT ) 
    public void setLimitationmethod( Integer limitationmethod ) {
        this.limitationmethod = limitationmethod;
    }
    public Integer getLimitationmethod() {
        return this.limitationmethod;
    }

    //--- DATABASE MAPPING : timezone ( VARCHAR ) 
    public void setTimezone( String timezone ) {
        this.timezone = timezone;
    }
    public String getTimezone() {
        return this.timezone;
    }

    //--- DATABASE MAPPING : maxAmount ( INT ) 
    public void setMaxamount( Integer maxamount ) {
        this.maxamount = maxamount;
    }
    public Integer getMaxamount() {
        return this.maxamount;
    }

    //--- DATABASE MAPPING : maxAmountPerPerson ( INT ) 
    public void setMaxamountperperson( Integer maxamountperperson ) {
        this.maxamountperperson = maxamountperperson;
    }
    public Integer getMaxamountperperson() {
        return this.maxamountperperson;
    }

    //--- DATABASE MAPPING : applyToAllStore ( INT ) 
    public void setApplytoallstore( Integer applytoallstore ) {
        this.applytoallstore = applytoallstore;
    }
    public Integer getApplytoallstore() {
        return this.applytoallstore;
    }

    //--- DATABASE MAPPING : applyToAllDish ( INT ) 
    public void setApplytoalldish( Integer applytoalldish ) {
        this.applytoalldish = applytoalldish;
    }
    public Integer getApplytoalldish() {
        return this.applytoalldish;
    }

    //--- DATABASE MAPPING : overlayUse ( INT ) 
    public void setOverlayuse( Integer overlayuse ) {
        this.overlayuse = overlayuse;
    }
    public Integer getOverlayuse() {
        return this.overlayuse;
    }

    //--- DATABASE MAPPING : value ( INT ) 
    public void setValue( Integer value ) {
        this.value = value;
    }
    public Integer getValue() {
        return this.value;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : status ( INT ) 
    public void setStatus( Integer status ) {
        this.status = status;
    }
    public Integer getStatus() {
        return this.status;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uid);
        sb.append("]:"); 
        sb.append(corpid);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(objecttosend);
        sb.append("|");
        sb.append(deliverystartdate);
        sb.append("|");
        sb.append(deliveryenddate);
        sb.append("|");
        sb.append(deliverystarttime);
        sb.append("|");
        sb.append(deliveryendtime);
        sb.append("|");
        sb.append(applystartdate);
        sb.append("|");
        sb.append(applyenddate);
        sb.append("|");
        sb.append(limitationmethod);
        sb.append("|");
        sb.append(timezone);
        sb.append("|");
        sb.append(maxamount);
        sb.append("|");
        sb.append(maxamountperperson);
        sb.append("|");
        sb.append(applytoallstore);
        sb.append("|");
        sb.append(applytoalldish);
        sb.append("|");
        sb.append(overlayuse);
        sb.append("|");
        sb.append(value);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(status);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 

}
