/*
 * Created on 11 五月 2015 ( Time 23:06:07 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.datajpa.business.service.impl;

import java.util.List;

import javax.annotation.Resource;

import com.dt.hippo.datajpa.model.jpa.Dishspecificationinfo;
import com.dt.hippo.datajpa.model.jpa.DishspecificationinfoKey;
import java.util.Date;
import com.dt.hippo.datajpa.business.service.DishspecificationinfoService;
import com.dt.hippo.datajpa.data.repository.jpa.DishspecificationinfoJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of DishspecificationinfoService
 */
@Component
@Transactional
public class DishspecificationinfoServiceImpl implements DishspecificationinfoService {

	@Resource
	private DishspecificationinfoJpaRepository dishspecificationinfoJpaRepository;

	
	@Override
    @Transactional(readOnly = true)
	public Dishspecificationinfo findById(Long dishid, Long uid) {
		DishspecificationinfoKey id = new DishspecificationinfoKey(dishid, uid);
		return dishspecificationinfoJpaRepository.findOne(id);
	}

	@Override
    @Transactional(readOnly = true)
	public List<Dishspecificationinfo> findAll() {
		return  dishspecificationinfoJpaRepository.findAll();
	}

	@Override
	public Dishspecificationinfo save(Dishspecificationinfo dishspecificationinfo) {
		return dishspecificationinfoJpaRepository.save(dishspecificationinfo) ;
	}

	@Override
	public Dishspecificationinfo create(Dishspecificationinfo dishspecificationinfo) {
		DishspecificationinfoKey id = new DishspecificationinfoKey(dishspecificationinfo.getDishid(), dishspecificationinfo.getUid());
		Dishspecificationinfo dishspecificationinfoExisted = dishspecificationinfoJpaRepository.findOne(id);
		if( dishspecificationinfoExisted != null ) {
			throw new IllegalStateException("already.exists");
		}
		return dishspecificationinfoJpaRepository.save(dishspecificationinfo);
	}

	@Override
	public Dishspecificationinfo update(Dishspecificationinfo dishspecificationinfo) {
		DishspecificationinfoKey id = new DishspecificationinfoKey(dishspecificationinfo.getDishid(), dishspecificationinfo.getUid());
		Dishspecificationinfo dishspecificationinfoExisted = dishspecificationinfoJpaRepository.findOne(id);
        if (dishspecificationinfoExisted == null) {
            throw new IllegalStateException("not exists");
        }
		return dishspecificationinfoJpaRepository.save(dishspecificationinfo);
	}

	@Override
	public void delete(Long dishid, Long uid) {
		DishspecificationinfoKey id = new DishspecificationinfoKey(dishid, uid);
		dishspecificationinfoJpaRepository.delete(id);
	}

	public DishspecificationinfoJpaRepository getDishspecificationinfoJpaRepository() {
		return dishspecificationinfoJpaRepository;
	}

	public void setDishspecificationinfoJpaRepository(DishspecificationinfoJpaRepository dishspecificationinfoJpaRepository) {
		this.dishspecificationinfoJpaRepository = dishspecificationinfoJpaRepository;
	}



}
