/*
 * Created on 11 五月 2015 ( Time 23:06:09 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.datajpa.business.service.impl;

import java.util.List;

import javax.annotation.Resource;

import com.dt.hippo.datajpa.model.jpa.Dishinfo;
import java.util.Date;
import java.util.List;
import com.dt.hippo.datajpa.business.service.DishinfoService;
import com.dt.hippo.datajpa.data.repository.jpa.DishinfoJpaRepository;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of DishinfoService
 */
@Component
@Transactional
public class DishinfoServiceImpl implements DishinfoService {

	@Resource
	private DishinfoJpaRepository dishinfoJpaRepository;

	
	@Override
    @Transactional(readOnly = true)
	public Dishinfo findById(Long uid) {
		return dishinfoJpaRepository.findOne(uid);
	}

	@Override
    @Transactional(readOnly = true)
	public List<Dishinfo> findAll() {
		return  dishinfoJpaRepository.findAll();
	}

	@Override
	public Dishinfo save(Dishinfo dishinfo) {
		return dishinfoJpaRepository.save(dishinfo) ;
	}

	@Override
	public Dishinfo create(Dishinfo dishinfo) {
		Dishinfo dishinfoExisted = dishinfoJpaRepository.findOne(dishinfo.getUid());
		if( dishinfoExisted != null ) {
			throw new IllegalStateException("already.exists");
		}
		return dishinfoJpaRepository.save(dishinfo);
	}

	@Override
	public Dishinfo update(Dishinfo dishinfo) {
		Dishinfo dishinfoExisted = dishinfoJpaRepository.findOne(dishinfo.getUid());
        if (dishinfoExisted == null) {
            throw new IllegalStateException("not exists");
        }
		return dishinfoJpaRepository.save(dishinfo);
	}

	@Override
	public void delete(Long uid) {
		dishinfoJpaRepository.delete(uid);
	}

	public DishinfoJpaRepository getDishinfoJpaRepository() {
		return dishinfoJpaRepository;
	}

	public void setDishinfoJpaRepository(DishinfoJpaRepository dishinfoJpaRepository) {
		this.dishinfoJpaRepository = dishinfoJpaRepository;
	}



}
