/*
 * Created on 12 五月 2015 ( Time 20:53:04 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.web.listitem;

import com.dt.hippo.auto.model.Orderdetail;
import com.dt.hippo.auto.web.common.ListItem;

public class OrderdetailListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public OrderdetailListItem(Orderdetail orderdetail) {
		super();

		this.value = ""
			 + orderdetail.getOrderno()
			 + "|"  + orderdetail.getUid()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = orderdetail.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
