/*
 * Created on 18 五月 2015 ( Time 11:07:15 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.web.listitem;

import com.dt.hippo.auto.model.Pointrule;
import com.dt.hippo.auto.web.common.ListItem;

public class PointruleListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PointruleListItem(Pointrule pointrule) {
		super();

		this.value = ""
			 + pointrule.getType()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = pointrule.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
