/*
 * Created on 13 五月 2015 ( Time 21:15:29 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.web.listitem;

import com.dt.hippo.auto.model.Promotiondetailinfo;
import com.dt.hippo.auto.web.common.ListItem;

public class PromotiondetailinfoListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public PromotiondetailinfoListItem(Promotiondetailinfo promotiondetailinfo) {
		super();

		this.value = ""
			 + promotiondetailinfo.getUid()
			 + "|"  + promotiondetailinfo.getDishid()
			 + "|"  + promotiondetailinfo.getSpecificationid()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = promotiondetailinfo.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
