/*
 * Created on 13 五月 2015 ( Time 21:15:31 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.web.listitem;

import com.dt.hippo.auto.model.Sequence;
import com.dt.hippo.auto.web.common.ListItem;

public class SequenceListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public SequenceListItem(Sequence sequence) {
		super();

		this.value = ""
			 + sequence.getUid()
			 + "|"  + sequence.getKeyword()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = sequence.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
