/*
 * Created on 18 五月 2015 ( Time 11:07:19 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.web.listitem;

import com.dt.hippo.auto.model.Targetlist;
import com.dt.hippo.auto.web.common.ListItem;

public class TargetlistListItem implements ListItem {

	private final String value ;
	private final String label ;
	
	public TargetlistListItem(Targetlist targetlist) {
		super();

		this.value = ""
			 + targetlist.getUid()
			 + "|"  + targetlist.getType()
			 + "|"  + targetlist.getCorpid()
			 + "|"  + targetlist.getTargetvalue()
		;

		//TODO : Define here the attributes to be displayed as the label
		this.label = targetlist.toString();
	}

	@Override
	public String getValue() {
		return value;
	}

	@Override
	public String getLabel() {
		return label;
	}

}
