/*
 * Created on 18 五月 2015 ( Time 11:07:08 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model;

import java.io.Serializable;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties({ "password", "externaluid", "createdate",
		"modifydate", "createuser", "modifyuser", "status",
		"platform", "password" })
public class Account extends
		com.dt.hippo.auto.model.base.Account implements
		Serializable
{

	private static final long serialVersionUID = 1L;
	// ----------------------------------------------------------------------
	// ENTITY LINKS ( RELATIONSHIP )
	// ----------------------------------------------------------------------

	// ----------------------------------------------------------------------
	// GETTERS & SETTERS FOR LINKS
	// ----------------------------------------------------------------------

}
