/*
 * Created on 19 五月 2015 ( Time 13:38:29 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model;

import java.io.Serializable;
import java.util.List;

public class Category extends com.dt.hippo.auto.model.base.Category implements Serializable {

    private static final long serialVersionUID = 1L;
     //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------


    protected List<Dishinfo> listOfDishinfo;
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------


	public List<Dishinfo> getListOfDishinfo()
	{
		return listOfDishinfo;
	}


	public void setListOfDishinfo(List<Dishinfo> listOfDishinfo)
	{
		this.listOfDishinfo = listOfDishinfo;
	}

}
