/*
 * Created on 14 五月 2015 ( Time 21:11:35 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model;

import java.io.Serializable;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators;
@JsonIdentityInfo(generator = ObjectIdGenerators.IntSequenceGenerator.class, 
property = "@uid")
public class Category extends com.dt.hippo.auto.model.base.Category implements Serializable {

    private static final long serialVersionUID = 1L;
     //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    protected List<Dishinfo> listOfDishinfo;



    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfDishinfo( List<Dishinfo> listOfDishinfo ) {
        this.listOfDishinfo = listOfDishinfo;
    }
    public List<Dishinfo> getListOfDishinfo() {
        return this.listOfDishinfo;
    }


}
