/*
 * Created on 18 五月 2015 ( Time 11:07:14 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model;

import java.io.Serializable;

import javax.validation.constraints.*;

import com.fasterxml.jackson.annotation.JsonIdentityInfo;
import com.fasterxml.jackson.annotation.ObjectIdGenerators.IntSequenceGenerator;

import java.util.*;
@JsonIdentityInfo(generator = IntSequenceGenerator.class)
public class Paymentlog extends com.dt.hippo.auto.model.base.Paymentlog implements Serializable {

    private static final long serialVersionUID = 1L;
     //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------



    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

}
