/*
 * Created on 18 五月 2015 ( Time 11:07:16 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model;

import java.io.Serializable;
import java.util.List;

public class Promotioninfo extends com.dt.hippo.auto.model.base.Promotioninfo implements Serializable {

    private static final long serialVersionUID = 1L;
     //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
	protected List<Promotiondetailinfo> listOfPromotiondetailinfo;
	public List<Promotiondetailinfo> getListOfPromotiondetailinfo()
	{
		return listOfPromotiondetailinfo;
	}
	public void setListOfPromotiondetailinfo(
			List<Promotiondetailinfo> listOfPromotiondetailinfo)
	{
		this.listOfPromotiondetailinfo = listOfPromotiondetailinfo;
	}

	private int priority;
	public int getPriority()
	{
		return priority;
	}
	public void setPriority(int priority)
	{
		this.priority = priority;
	}

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------

}
