/*
 * Created on 14 五月 2015 ( Time 21:11:36 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model;

import java.io.Serializable;

import javax.validation.constraints.*;
import java.util.*;
import java.util.Date;

public class Promotiondetailinfo extends com.dt.hippo.auto.model.base.Promotiondetailinfo implements Serializable {

    private static final long serialVersionUID = 1L;
     //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    protected Dishinfo dishinfo    ;
    protected Dishspecificationinfo dishspecificationinfo;



    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDishinfo( Dishinfo dishinfo ) {
        this.dishinfo = dishinfo;
    }
    public Dishinfo getDishinfo() {
        return this.dishinfo;
    }

    public void setDishspecificationinfo( Dishspecificationinfo dishspecificationinfo ) {
        this.dishspecificationinfo = dishspecificationinfo;
    }
    public Dishspecificationinfo getDishspecificationinfo() {
        return this.dishspecificationinfo;
    }


}
