/*
 * Created on 12 五月 2015 ( Time 20:53:08 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model;

import java.io.Serializable;

import javax.validation.constraints.*;

import java.util.Date;

public class Storeinfo implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @NotNull
    protected Long uid;

    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    

    protected Long parentcorpid;

    @Size( max = 32 )
    protected String storeno;

    @Size( max = 200 )
    protected String storename;

    @Size( max = 1000 )
    protected String storedescription;

    @Size( max = 20 )
    protected String cityid;

    @Size( max = 400 )
    protected String address;

    @Size( max = 50 )
    protected String phone;


    protected Byte type;

    @Size( max = 200 )
    protected String businesshours;

    @Size( max = 200 )
    protected String deliverydescription;


    protected Integer ordercount;


    protected Double lng;


    protected Double lat;


    protected Date createdate;


    protected Date modifydate;

    @Size( max = 50 )
    protected String createuser;

    @Size( max = 50 )
    protected String modifyuser;


    protected Byte delflg;

    @Size( max = 50 )
    protected String platform;



    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }

    public Long getUid() {
        return this.uid;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    public void setParentcorpid( Long parentcorpid ) {
        this.parentcorpid = parentcorpid;
    }
    public Long getParentcorpid() {
        return this.parentcorpid;
    }

    public void setStoreno( String storeno ) {
        this.storeno = storeno;
    }
    public String getStoreno() {
        return this.storeno;
    }

    public void setStorename( String storename ) {
        this.storename = storename;
    }
    public String getStorename() {
        return this.storename;
    }

    public void setStoredescription( String storedescription ) {
        this.storedescription = storedescription;
    }
    public String getStoredescription() {
        return this.storedescription;
    }

    public void setCityid( String cityid ) {
        this.cityid = cityid;
    }
    public String getCityid() {
        return this.cityid;
    }

    public void setAddress( String address ) {
        this.address = address;
    }
    public String getAddress() {
        return this.address;
    }

    public void setPhone( String phone ) {
        this.phone = phone;
    }
    public String getPhone() {
        return this.phone;
    }

    public void setType( Byte type ) {
        this.type = type;
    }
    public Byte getType() {
        return this.type;
    }

    public void setBusinesshours( String businesshours ) {
        this.businesshours = businesshours;
    }
    public String getBusinesshours() {
        return this.businesshours;
    }

    public void setDeliverydescription( String deliverydescription ) {
        this.deliverydescription = deliverydescription;
    }
    public String getDeliverydescription() {
        return this.deliverydescription;
    }

    public void setOrdercount( Integer ordercount ) {
        this.ordercount = ordercount;
    }
    public Integer getOrdercount() {
        return this.ordercount;
    }

    public void setLng( Double lng ) {
        this.lng = lng;
    }
    public Double getLng() {
        return this.lng;
    }

    public void setLat( Double lat ) {
        this.lat = lat;
    }
    public Double getLat() {
        return this.lat;
    }

    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    public void setDelflg( Byte delflg ) {
        this.delflg = delflg;
    }
    public Byte getDelflg() {
        return this.delflg;
    }

    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
 
        public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(uid);
        sb.append("|");
        sb.append(parentcorpid);
        sb.append("|");
        sb.append(storeno);
        sb.append("|");
        sb.append(storename);
        sb.append("|");
        sb.append(storedescription);
        sb.append("|");
        sb.append(cityid);
        sb.append("|");
        sb.append(address);
        sb.append("|");
        sb.append(phone);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(businesshours);
        sb.append("|");
        sb.append(deliverydescription);
        sb.append("|");
        sb.append(ordercount);
        sb.append("|");
        sb.append(lng);
        sb.append("|");
        sb.append(lat);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(delflg);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 


}
