/*
 * Created on 18 五月 2015 ( Time 11:12:58 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.rest.controller;

import java.util.LinkedList;
import java.util.List;

import javax.annotation.Resource;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.ResponseStatus;
import com.dt.hippo.auto.model.Dishprice;
import com.dt.hippo.auto.business.service.DishpriceService;
import com.dt.hippo.auto.web.listitem.DishpriceListItem;

/**
 * Spring MVC controller for 'Dishprice' management.
 */
@Controller
@RequestMapping("/api")
public class DishpriceRestController {

	@Resource
	protected DishpriceService dishpriceService;
	
	@RequestMapping( value="/items/dishprice",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<DishpriceListItem> findAllAsListItems() {
		List<Dishprice> list = dishpriceService.findAll();
		List<DishpriceListItem> items = new LinkedList<DishpriceListItem>();
		for ( Dishprice dishprice : list ) {
			items.add(new DishpriceListItem( dishprice ) );
		}
		return items;
	}
	
	@RequestMapping( value="/dishprice",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public List<Dishprice> findAll() {
		return dishpriceService.findAll();
	}

	@RequestMapping( value="/dishprice/{uid}",
			method = RequestMethod.GET,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Dishprice findOne(@PathVariable("uid") Long uid) {
		return dishpriceService.findById(uid);
	}
	
	@RequestMapping( value="/dishprice",
			method = RequestMethod.POST,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Dishprice create(@RequestBody Dishprice dishprice) {
		return dishpriceService.create(dishprice);
	}

	@RequestMapping( value="/dishprice/{uid}",
			method = RequestMethod.PUT,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public Dishprice update(@PathVariable("uid") Long uid, @RequestBody Dishprice dishprice) {
		return dishpriceService.update(dishprice);
	}

	@RequestMapping( value="/dishprice/{uid}",
			method = RequestMethod.DELETE,
			produces = MediaType.APPLICATION_JSON_VALUE)
    @ResponseStatus(HttpStatus.OK)
	@ResponseBody
	public void delete(@PathVariable("uid") Long uid) {
		dishpriceService.delete(uid);
	}
	
}
