/*
 * Created on 21 ���� 2014 ( Time 16:05:25 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.datajpa.model.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "ContactHobbyDetail" ( stored in table "CONTACT_HOBBY_DETAIL" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class ContactHobbyDetailKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="CONTACT_ID", nullable=false)
    private Integer    contactId    ;
    
    @Column(name="HOBBY_ID", nullable=false, length=20)
    private String     hobbyId      ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public ContactHobbyDetailKey() {
        super();
    }

    public ContactHobbyDetailKey( Integer contactId, String hobbyId ) {
        super();
        this.contactId = contactId ;
        this.hobbyId = hobbyId ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setContactId( Integer value ) {
        this.contactId = value;
    }
    public Integer getContactId() {
        return this.contactId;
    }

    public void setHobbyId( String value ) {
        this.hobbyId = value;
    }
    public String getHobbyId() {
        return this.hobbyId;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		ContactHobbyDetailKey other = (ContactHobbyDetailKey) obj; 
		//--- Attribute contactId
		if ( contactId == null ) { 
			if ( other.contactId != null ) 
				return false ; 
		} else if ( ! contactId.equals(other.contactId) ) 
			return false ; 
		//--- Attribute hobbyId
		if ( hobbyId == null ) { 
			if ( other.hobbyId != null ) 
				return false ; 
		} else if ( ! hobbyId.equals(other.hobbyId) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute contactId
		result = prime * result + ((contactId == null) ? 0 : contactId.hashCode() ) ; 
		//--- Attribute hobbyId
		result = prime * result + ((hobbyId == null) ? 0 : hobbyId.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(contactId); 
		sb.append("|"); 
		sb.append(hobbyId); 
        return sb.toString();
    }
}
