/*
 * Created on 21 ���� 2014 ( Time 16:05:25 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.datajpa.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;


import javax.persistence.*;

/**
 * Persistent class for entity stored in table "CONTACT_TEL_DETAIL"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="CONTACT_TEL_DETAIL", catalog="hippo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="ContactTelDetail.countAll", query="SELECT COUNT(x) FROM ContactTelDetail x" )
} )
public class ContactTelDetail implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="ID", nullable=false)
    private Integer    id           ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="TEL_TYPE", nullable=false, length=20)
    private String     telType      ;

    @Column(name="TEL_NUMBER", nullable=false, length=20)
    private String     telNumber    ;

    @Column(name="VERSION", nullable=false)
    private Integer    version      ;

	// "contactId" (column "CONTACT_ID") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="CONTACT_ID", referencedColumnName="ID")
    private Contact contact     ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public ContactTelDetail() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setId( Integer id ) {
        this.id = id ;
    }
    public Integer getId() {
        return this.id;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : TEL_TYPE ( VARCHAR ) 
    public void setTelType( String telType ) {
        this.telType = telType;
    }
    public String getTelType() {
        return this.telType;
    }

    //--- DATABASE MAPPING : TEL_NUMBER ( VARCHAR ) 
    public void setTelNumber( String telNumber ) {
        this.telNumber = telNumber;
    }
    public String getTelNumber() {
        return this.telNumber;
    }

    //--- DATABASE MAPPING : VERSION ( INT ) 
    public void setVersion( Integer version ) {
        this.version = version;
    }
    public Integer getVersion() {
        return this.version;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setContact( Contact contact ) {
        this.contact = contact;
    }
    public Contact getContact() {
        return this.contact;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(id);
        sb.append("]:"); 
        sb.append(telType);
        sb.append("|");
        sb.append(telNumber);
        sb.append("|");
        sb.append(version);
        return sb.toString(); 
    } 

}
