/*
 * Created on 18 五月 2015 ( Time 11:07:11 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

//import com.dt.hippo.auto.model.jpa.base.DishspecificationinfoEntity;
/**
 * Persistent class for entity stored in table "dishSpecificationInfo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="dishSpecificationInfo", catalog="hippo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DishspecificationinfoEntity.countAll", query="SELECT COUNT(x) FROM DishspecificationinfoEntity x" )
} )
@AttributeOverrides({
 @AttributeOverride(name = "dishid", column = @Column(name = "dishId", insertable = false, updatable = false))

})
public class DishspecificationinfoEntity extends com.dt.hippo.auto.model.jpa.base.DishspecificationinfoEntity implements Serializable {

   protected static final long serialVersionUID = 8L;

     //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name="dishId", referencedColumnName="uid")
    protected DishinfoEntity dishinfo    ;
    @OneToMany(mappedBy="dishspecificationinfo", targetEntity=DishpriceEntity.class)
    protected List<DishpriceEntity> listOfDishprice;
    @OneToMany(mappedBy="dishspecificationinfo", targetEntity=ComboinfoEntity.class)
    protected List<ComboinfoEntity> listOfComboinfo;
    @OneToMany(mappedBy="dishspecificationinfo", targetEntity=PromotiondetailinfoEntity.class)
    protected List<PromotiondetailinfoEntity> listOfPromotiondetailinfo;


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setDishinfo( DishinfoEntity dishinfo ) {
        this.dishinfo = dishinfo;
    }
    public DishinfoEntity getDishinfo() {
        return this.dishinfo;
    }

    public void setListOfDishprice( List<DishpriceEntity> listOfDishprice ) {
        this.listOfDishprice = listOfDishprice;
    }
    public List<DishpriceEntity> getListOfDishprice() {
        return this.listOfDishprice;
    }

    public void setListOfComboinfo( List<ComboinfoEntity> listOfComboinfo ) {
        this.listOfComboinfo = listOfComboinfo;
    }
    public List<ComboinfoEntity> getListOfComboinfo() {
        return this.listOfComboinfo;
    }

    public void setListOfPromotiondetailinfo( List<PromotiondetailinfoEntity> listOfPromotiondetailinfo ) {
        this.listOfPromotiondetailinfo = listOfPromotiondetailinfo;
    }
    public List<PromotiondetailinfoEntity> getListOfPromotiondetailinfo() {
        return this.listOfPromotiondetailinfo;
    }


}
