/*
 * Created on 12 五月 2015 ( Time 20:53:02 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

/**
 * Persistent class for entity stored in table "dishinfo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="dishinfo", catalog="hippo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DishinfoEntity.countAll", query="SELECT COUNT(x) FROM DishinfoEntity x" )
} )
public class DishinfoEntity implements Serializable {

    protected static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    //----------------------------------------------------------------------
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="uid", nullable=false)
    protected Long       uid          ;


    //----------------------------------------------------------------------
    // ENTITY DATA FIELDS 
    //----------------------------------------------------------------------    
    @Column(name="no", length=10)
    protected String     no           ;

    @Column(name="dishName", length=200)
    protected String     dishname     ;

    @Column(name="dishDescription", length=300)
    protected String     dishdescription ;

    @Column(name="imageUrl", length=300)
    protected String     imageurl     ;

    @Column(name="price")
    protected Double     price        ;

    @Column(name="type")
    protected Byte       type         ;

    @Column(name="hasSpecification")
    protected Byte       hasspecification ;

    @Column(name="startDate")
    protected Integer    startdate    ;

    @Column(name="endDate")
    protected Integer    enddate      ;

    @Column(name="paused")
    protected Byte       paused       ;

    @Column(name="promotionTime")
    protected Integer    promotiontime ;

    @Column(name="promotionEndTime")
    protected Integer    promotionendtime ;

    @Column(name="promotionPrice")
    protected Double     promotionprice ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="createDate")
    protected Date       createdate   ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="modifyDate")
    protected Date       modifydate   ;

    @Column(name="createUser", length=50)
    protected String     createuser   ;

    @Column(name="modifyUser", length=50)
    protected String     modifyuser   ;

    @Column(name="delFlg")
    protected Byte       delflg       ;

    @Column(name="platform", length=50)
    protected String     platform     ;

	// "corpid" (column "corpId") is not defined by itself because used as FK in a link 
	// "categoryid" (column "categoryId") is not defined by itself because used as FK in a link 


    //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @OneToMany(mappedBy="dishinfo", targetEntity=ComboinfoEntity.class)
    protected List<ComboinfoEntity> listOfComboinfo;

    @OneToMany(mappedBy="dishinfo", targetEntity=DishspecificationinfoEntity.class)
    protected List<DishspecificationinfoEntity> listOfDishspecificationinfo;

    @ManyToOne
    @JoinColumns( { 
        @JoinColumn(name="corpId", referencedColumnName="corpId"),
        @JoinColumn(name="categoryId", referencedColumnName="uid") } )
    protected CategoryEntity category    ;


    //----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    //----------------------------------------------------------------------
    public DishinfoEntity() {
		super();
    }
    
    //----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    //----------------------------------------------------------------------
    public void setUid( Long uid ) {
        this.uid = uid ;
    }
    public Long getUid() {
        return this.uid;
    }

    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : no ( VARCHAR ) 
    public void setNo( String no ) {
        this.no = no;
    }
    public String getNo() {
        return this.no;
    }

    //--- DATABASE MAPPING : dishName ( VARCHAR ) 
    public void setDishname( String dishname ) {
        this.dishname = dishname;
    }
    public String getDishname() {
        return this.dishname;
    }

    //--- DATABASE MAPPING : dishDescription ( VARCHAR ) 
    public void setDishdescription( String dishdescription ) {
        this.dishdescription = dishdescription;
    }
    public String getDishdescription() {
        return this.dishdescription;
    }

    //--- DATABASE MAPPING : imageUrl ( VARCHAR ) 
    public void setImageurl( String imageurl ) {
        this.imageurl = imageurl;
    }
    public String getImageurl() {
        return this.imageurl;
    }

    //--- DATABASE MAPPING : price ( DOUBLE ) 
    public void setPrice( Double price ) {
        this.price = price;
    }
    public Double getPrice() {
        return this.price;
    }

    //--- DATABASE MAPPING : type ( TINYINT ) 
    public void setType( Byte type ) {
        this.type = type;
    }
    public Byte getType() {
        return this.type;
    }

    //--- DATABASE MAPPING : hasSpecification ( TINYINT ) 
    public void setHasspecification( Byte hasspecification ) {
        this.hasspecification = hasspecification;
    }
    public Byte getHasspecification() {
        return this.hasspecification;
    }

    //--- DATABASE MAPPING : startDate ( INT ) 
    public void setStartdate( Integer startdate ) {
        this.startdate = startdate;
    }
    public Integer getStartdate() {
        return this.startdate;
    }

    //--- DATABASE MAPPING : endDate ( INT ) 
    public void setEnddate( Integer enddate ) {
        this.enddate = enddate;
    }
    public Integer getEnddate() {
        return this.enddate;
    }

    //--- DATABASE MAPPING : paused ( TINYINT ) 
    public void setPaused( Byte paused ) {
        this.paused = paused;
    }
    public Byte getPaused() {
        return this.paused;
    }

    //--- DATABASE MAPPING : promotionTime ( INT ) 
    public void setPromotiontime( Integer promotiontime ) {
        this.promotiontime = promotiontime;
    }
    public Integer getPromotiontime() {
        return this.promotiontime;
    }

    //--- DATABASE MAPPING : promotionEndTime ( INT ) 
    public void setPromotionendtime( Integer promotionendtime ) {
        this.promotionendtime = promotionendtime;
    }
    public Integer getPromotionendtime() {
        return this.promotionendtime;
    }

    //--- DATABASE MAPPING : promotionPrice ( DOUBLE ) 
    public void setPromotionprice( Double promotionprice ) {
        this.promotionprice = promotionprice;
    }
    public Double getPromotionprice() {
        return this.promotionprice;
    }

    //--- DATABASE MAPPING : createDate ( DATETIME ) 
    public void setCreatedate( Date createdate ) {
        this.createdate = createdate;
    }
    public Date getCreatedate() {
        return this.createdate;
    }

    //--- DATABASE MAPPING : modifyDate ( DATETIME ) 
    public void setModifydate( Date modifydate ) {
        this.modifydate = modifydate;
    }
    public Date getModifydate() {
        return this.modifydate;
    }

    //--- DATABASE MAPPING : createUser ( VARCHAR ) 
    public void setCreateuser( String createuser ) {
        this.createuser = createuser;
    }
    public String getCreateuser() {
        return this.createuser;
    }

    //--- DATABASE MAPPING : modifyUser ( VARCHAR ) 
    public void setModifyuser( String modifyuser ) {
        this.modifyuser = modifyuser;
    }
    public String getModifyuser() {
        return this.modifyuser;
    }

    //--- DATABASE MAPPING : delFlg ( TINYINT ) 
    public void setDelflg( Byte delflg ) {
        this.delflg = delflg;
    }
    public Byte getDelflg() {
        return this.delflg;
    }

    //--- DATABASE MAPPING : platform ( VARCHAR ) 
    public void setPlatform( String platform ) {
        this.platform = platform;
    }
    public String getPlatform() {
        return this.platform;
    }


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setListOfComboinfo( List<ComboinfoEntity> listOfComboinfo ) {
        this.listOfComboinfo = listOfComboinfo;
    }
    public List<ComboinfoEntity> getListOfComboinfo() {
        return this.listOfComboinfo;
    }

    public void setListOfDishspecificationinfo( List<DishspecificationinfoEntity> listOfDishspecificationinfo ) {
        this.listOfDishspecificationinfo = listOfDishspecificationinfo;
    }
    public List<DishspecificationinfoEntity> getListOfDishspecificationinfo() {
        return this.listOfDishspecificationinfo;
    }

    public void setCategory( CategoryEntity category ) {
        this.category = category;
    }
    public CategoryEntity getCategory() {
        return this.category;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append("["); 
        sb.append(uid);
        sb.append("]:"); 
        sb.append(no);
        sb.append("|");
        sb.append(dishname);
        sb.append("|");
        sb.append(dishdescription);
        sb.append("|");
        sb.append(imageurl);
        sb.append("|");
        sb.append(price);
        sb.append("|");
        sb.append(type);
        sb.append("|");
        sb.append(hasspecification);
        sb.append("|");
        sb.append(startdate);
        sb.append("|");
        sb.append(enddate);
        sb.append("|");
        sb.append(paused);
        sb.append("|");
        sb.append(promotiontime);
        sb.append("|");
        sb.append(promotionendtime);
        sb.append("|");
        sb.append(promotionprice);
        sb.append("|");
        sb.append(createdate);
        sb.append("|");
        sb.append(modifydate);
        sb.append("|");
        sb.append(createuser);
        sb.append("|");
        sb.append(modifyuser);
        sb.append("|");
        sb.append(delflg);
        sb.append("|");
        sb.append(platform);
        return sb.toString(); 
    } 

}
