/*
 * Created on 14 五月 2015 ( Time 15:58:50 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
// This Bean has a basic Primary Key (not composite) 

package com.dt.hippo.auto.model.jpa;

import java.io.Serializable;

//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;

import java.util.Date;
import java.util.List;

import javax.persistence.*;

//import com.dt.hippo.auto.model.jpa.base.DishinfoEntity;
/**
 * Persistent class for entity stored in table "dishinfo"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name="dishinfo", catalog="hippo" )
// Define named queries here
@NamedQueries ( {
  @NamedQuery ( name="DishinfoEntity.countAll", query="SELECT COUNT(x) FROM DishinfoEntity x" )
} )
@AttributeOverrides({
 @AttributeOverride(name = "corpid", column = @Column(name = "corpId", insertable = false, updatable = false))
 ,  @AttributeOverride(name = "categoryid", column = @Column(name = "categoryId", insertable = false, updatable = false))

})
public class DishinfoEntity extends com.dt.hippo.auto.model.jpa.base.DishinfoEntity implements Serializable {

   protected static final long serialVersionUID = 8L;

     //----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    //----------------------------------------------------------------------
    @ManyToOne
    @JoinColumns( { 
        @JoinColumn(name="corpId", referencedColumnName="corpId"),
        @JoinColumn(name="categoryId", referencedColumnName="uid") } )
    protected CategoryEntity category    ;
    @OneToMany(mappedBy="mainDishinfo", targetEntity=ComboinfoEntity.class)
    protected List<ComboinfoEntity> listOfComboinfo;
    @OneToMany(mappedBy="dishinfo", targetEntity=DishspecificationinfoEntity.class)
    protected List<DishspecificationinfoEntity> listOfDishspecificationinfo;
    @OneToMany(mappedBy="dishinfo", targetEntity=PromotiondetailinfoEntity.class)
    protected List<PromotiondetailinfoEntity> listOfPromotiondetailinfo;


    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    //----------------------------------------------------------------------
    public void setCategory( CategoryEntity category ) {
        this.category = category;
    }
    public CategoryEntity getCategory() {
        return this.category;
    }



    public void setListOfDishspecificationinfo( List<DishspecificationinfoEntity> listOfDishspecificationinfo ) {
        this.listOfDishspecificationinfo = listOfDishspecificationinfo;
    }
    public List<DishspecificationinfoEntity> getListOfDishspecificationinfo() {
        return this.listOfDishspecificationinfo;
    }

    public void setListOfComboinfo( List<ComboinfoEntity> listOfComboinfo ) {
        this.listOfComboinfo = listOfComboinfo;
    }
    public List<ComboinfoEntity> getListOfComboinfo() {
        return this.listOfComboinfo;
    }

    public void setListOfPromotiondetailinfo( List<PromotiondetailinfoEntity> listOfPromotiondetailinfo ) {
        this.listOfPromotiondetailinfo = listOfPromotiondetailinfo;
    }
    public List<PromotiondetailinfoEntity> getListOfPromotiondetailinfo() {
        return this.listOfPromotiondetailinfo;
    }


}
