/*
 * Created on 18 五月 2015 ( Time 11:07:18 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "TargetlistEntity" ( stored in table "targetList" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class TargetlistEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="uid", nullable=false)
    protected Long       uid          ;
    
    @Column(name="type", nullable=false)
    protected Integer    type         ;
    
    @Column(name="corpId", nullable=false)
    protected Long       corpid       ;
    
    @Column(name="targetValue", nullable=false)
    protected Long       targetvalue  ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public TargetlistEntityKey() {
        super();
    }

    public TargetlistEntityKey( Long uid, Integer type, Long corpid, Long targetvalue ) {
        super();
        this.uid = uid ;
        this.type = type ;
        this.corpid = corpid ;
        this.targetvalue = targetvalue ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setUid( Long value ) {
        this.uid = value;
    }
    public Long getUid() {
        return this.uid;
    }

    public void setType( Integer value ) {
        this.type = value;
    }
    public Integer getType() {
        return this.type;
    }

    public void setCorpid( Long value ) {
        this.corpid = value;
    }
    public Long getCorpid() {
        return this.corpid;
    }

    public void setTargetvalue( Long value ) {
        this.targetvalue = value;
    }
    public Long getTargetvalue() {
        return this.targetvalue;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		TargetlistEntityKey other = (TargetlistEntityKey) obj; 
		//--- Attribute uid
		if ( uid == null ) { 
			if ( other.uid != null ) 
				return false ; 
		} else if ( ! uid.equals(other.uid) ) 
			return false ; 
		//--- Attribute type
		if ( type == null ) { 
			if ( other.type != null ) 
				return false ; 
		} else if ( ! type.equals(other.type) ) 
			return false ; 
		//--- Attribute corpid
		if ( corpid == null ) { 
			if ( other.corpid != null ) 
				return false ; 
		} else if ( ! corpid.equals(other.corpid) ) 
			return false ; 
		//--- Attribute targetvalue
		if ( targetvalue == null ) { 
			if ( other.targetvalue != null ) 
				return false ; 
		} else if ( ! targetvalue.equals(other.targetvalue) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute uid
		result = prime * result + ((uid == null) ? 0 : uid.hashCode() ) ; 
		//--- Attribute type
		result = prime * result + ((type == null) ? 0 : type.hashCode() ) ; 
		//--- Attribute corpid
		result = prime * result + ((corpid == null) ? 0 : corpid.hashCode() ) ; 
		//--- Attribute targetvalue
		result = prime * result + ((targetvalue == null) ? 0 : targetvalue.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(uid); 
		sb.append("|"); 
		sb.append(type); 
		sb.append("|"); 
		sb.append(corpid); 
		sb.append("|"); 
		sb.append(targetvalue); 
        return sb.toString();
    }
}
