/*
 * Created on 18 五月 2015 ( Time 11:07:20 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.model.jpa;
import java.io.Serializable;

import javax.persistence.*;

/**
 * Composite primary key for entity "VouchergeneratorinfoEntity" ( stored in table "voucherGeneratorInfo" )
 *
 * @author Telosys Tools Generator
 *
 */
 @Embeddable
public class VouchergeneratorinfoEntityKey implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY KEY ATTRIBUTES 
    //----------------------------------------------------------------------
    @Column(name="uid", nullable=false)
    protected Integer    uid          ;
    
    @Column(name="value", nullable=false)
    protected Integer    value        ;
    

    //----------------------------------------------------------------------
    // CONSTRUCTORS
    //----------------------------------------------------------------------
    public VouchergeneratorinfoEntityKey() {
        super();
    }

    public VouchergeneratorinfoEntityKey( Integer uid, Integer value ) {
        super();
        this.uid = uid ;
        this.value = value ;
    }
    
    //----------------------------------------------------------------------
    // GETTERS & SETTERS FOR KEY FIELDS
    //----------------------------------------------------------------------
    public void setUid( Integer value ) {
        this.uid = value;
    }
    public Integer getUid() {
        return this.uid;
    }

    public void setValue( Integer value ) {
        this.value = value;
    }
    public Integer getValue() {
        return this.value;
    }


    //----------------------------------------------------------------------
    // equals METHOD
    //----------------------------------------------------------------------
	public boolean equals(Object obj) { 
		if ( this == obj ) return true ; 
		if ( obj == null ) return false ;
		if ( this.getClass() != obj.getClass() ) return false ; 
		VouchergeneratorinfoEntityKey other = (VouchergeneratorinfoEntityKey) obj; 
		//--- Attribute uid
		if ( uid == null ) { 
			if ( other.uid != null ) 
				return false ; 
		} else if ( ! uid.equals(other.uid) ) 
			return false ; 
		//--- Attribute value
		if ( value == null ) { 
			if ( other.value != null ) 
				return false ; 
		} else if ( ! value.equals(other.value) ) 
			return false ; 
		return true; 
	} 


    //----------------------------------------------------------------------
    // hashCode METHOD
    //----------------------------------------------------------------------
	public int hashCode() { 
		final int prime = 31; 
		int result = 1; 
		
		//--- Attribute uid
		result = prime * result + ((uid == null) ? 0 : uid.hashCode() ) ; 
		//--- Attribute value
		result = prime * result + ((value == null) ? 0 : value.hashCode() ) ; 
		
		return result; 
	} 


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() {
		StringBuffer sb = new StringBuffer(); 
		sb.append(uid); 
		sb.append("|"); 
		sb.append(value); 
        return sb.toString();
    }
}
