/*
 * Created on 18 五月 2015 ( Time 11:07:10 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.dt.hippo.auto.business.service.impl;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Resource;

import com.dt.hippo.auto.model.Dishprice;
import com.dt.hippo.auto.model.jpa.DishpriceEntity;
import java.util.Date;
import com.dt.hippo.auto.business.service.DishpriceService;
import com.dt.hippo.auto.business.service.mapping.DishpriceServiceMapper;
import com.dt.hippo.auto.data.repository.jpa.DishpriceJpaRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * Implementation of DishpriceService
 */
@Service("dishpriceService")
@Transactional
public class DishpriceServiceImpl implements DishpriceService {

	@Resource
	protected DishpriceJpaRepository dishpriceJpaRepository;

	@Resource
	protected DishpriceServiceMapper dishpriceServiceMapper;
	
	@Override
	public Dishprice findById(Long uid) {
		DishpriceEntity dishpriceEntity = dishpriceJpaRepository.findOne(uid);
		return dishpriceServiceMapper.mapDishpriceEntityToDishprice(dishpriceEntity);
	}

	@Override
	public List<Dishprice> findAll() {
		Iterable<DishpriceEntity> entities = dishpriceJpaRepository.findAll();
		List<Dishprice> beans = new ArrayList<Dishprice>();
		for(DishpriceEntity dishpriceEntity : entities) {
			beans.add(dishpriceServiceMapper.mapDishpriceEntityToDishprice(dishpriceEntity));
		}
		return beans;
	}

	@Override
	public Dishprice save(Dishprice dishprice) {
		return update(dishprice) ;
	}

	@Override
	public Dishprice create(Dishprice dishprice) {
//		DishpriceEntity dishpriceEntity = dishpriceJpaRepository.findOne(dishprice.getUid());
//		if( dishpriceEntity != null ) {
//			throw new IllegalStateException("already.exists");
//		}
		DishpriceEntity dishpriceEntity = new DishpriceEntity();
		dishpriceServiceMapper.mapDishpriceToDishpriceEntity(dishprice, dishpriceEntity);
		DishpriceEntity dishpriceEntitySaved = dishpriceJpaRepository.save(dishpriceEntity);
		return dishpriceServiceMapper.mapDishpriceEntityToDishprice(dishpriceEntitySaved);
	}

	@Override
	public Dishprice update(Dishprice dishprice) {
		DishpriceEntity dishpriceEntity = dishpriceJpaRepository.findOne(dishprice.getUid());
		dishpriceServiceMapper.mapDishpriceToDishpriceEntity(dishprice, dishpriceEntity);
		DishpriceEntity dishpriceEntitySaved = dishpriceJpaRepository.save(dishpriceEntity);
		return dishpriceServiceMapper.mapDishpriceEntityToDishprice(dishpriceEntitySaved);
	}

	@Override
	public void delete(Long uid) {
		dishpriceJpaRepository.delete(uid);
	}

	public DishpriceJpaRepository getDishpriceJpaRepository() {
		return dishpriceJpaRepository;
	}

	public void setDishpriceJpaRepository(DishpriceJpaRepository dishpriceJpaRepository) {
		this.dishpriceJpaRepository = dishpriceJpaRepository;
	}

	public DishpriceServiceMapper getDishpriceServiceMapper() {
		return dishpriceServiceMapper;
	}

	public void setDishpriceServiceMapper(DishpriceServiceMapper dishpriceServiceMapper) {
		this.dishpriceServiceMapper = dishpriceServiceMapper;
	}

}
